#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative "lexer"

require './retina_ast.rb'

class SyntacticError < RuntimeError

    def initialize(tok)
        @token = tok
    end

    def to_s
        if @token.eql? "$" then
            "Unexpected EOF"
        else
           " Línea #{@token.position[0]}, Column #{@token.position[1]}: token inesperado : #{@token.symbol} : #{@token.id}"
        end
    end
end

class Parser < Racc::Parser

module_eval(<<'...end retina_parser.y/module_eval...', 'retina_parser.y', 226)


def on_error(id, token, stack)
    raise SyntacticError::new(token)
end

def initialize(lexer)
  @lexer=lexer
end

def next_token
    if ((token = @lexer.next_token)!=nil)
        return [token.symbol,token]
    else 
        return nil
    end

end


def parse(lexer)
	@yydebug = true
	@lexer = lexer
	@tokens = []
	do_parse
	
end
...end retina_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    60,    61,    62,    63,    37,   -12,    33,    44,    45,    34,
    68,    76,    67,    35,    36,    37,     5,    33,    43,    75,
    34,    37,   149,    33,    35,    36,    34,   150,   129,     6,
    35,    36,    94,     7,    74,    69,    73,    72,    71,    70,
    95,   -12,    66,    65,    64,    96,     5,    75,    10,   133,
    15,    55,    11,    95,    37,    39,    33,    62,    63,    34,
    40,    15,    55,    35,    36,    44,    45,    15,    55,    44,
    45,    14,    13,    31,    44,    45,    28,    29,    30,    10,
    21,    22,    23,    58,    37,    10,    33,    18,    85,    34,
    44,    45,    86,    35,    36,    44,    45,    66,    65,    64,
    15,    14,    13,    31,    87,    88,    28,    29,    30,    10,
    21,    22,    23,    93,    37,    76,    33,    18,   117,    34,
   121,    10,   123,    35,    36,   126,   128,   132,   139,   140,
    15,    14,    13,    31,   141,    10,    28,    29,    30,   146,
    21,    22,    23,    37,   148,    33,   151,    18,    34,    37,
   154,    33,    35,    36,    34,   129,   155,   157,    35,    36,
    15,    37,   158,    33,   163,   164,    34,    37,   165,    33,
    35,    36,    34,    37,   167,    33,    35,    36,    34,   168,
   170,   171,    35,    36,    62,    63,   nil,   nil,    37,    49,
    33,   nil,   nil,    34,    37,    49,    33,    35,    36,    34,
    37,   nil,    33,    35,    36,    34,    37,    49,    33,    35,
    36,    34,    37,    49,    33,    35,    36,    34,    37,    49,
    33,    35,    36,    34,    66,    65,    64,    35,    36,   nil,
   nil,   nil,   nil,    37,    49,    33,   nil,   nil,    34,    37,
    49,    33,    35,    36,    34,    37,    49,    33,    35,    36,
    34,    37,    49,    33,    35,    36,    34,    37,    49,    33,
    35,    36,    34,    37,    49,    33,    35,    36,    34,   nil,
   nil,   nil,    35,    36,   nil,   nil,   nil,   nil,    37,    49,
    33,   nil,   nil,    34,    37,    49,    33,    35,    36,    34,
    37,    49,    33,    35,    36,    34,    37,    49,    33,    35,
    36,    34,    37,    49,    33,    35,    36,    34,    37,    49,
    33,    35,    36,    34,   114,   nil,   nil,    35,    36,   nil,
   nil,   nil,   nil,   nil,    49,   nil,   nil,   nil,   nil,    37,
    49,    33,   nil,   nil,    34,   nil,    49,   nil,    35,    36,
   nil,    37,    49,    33,   nil,   nil,    34,   nil,    49,   nil,
    35,    36,   nil,   nil,    49,   nil,   nil,   nil,    14,    13,
    31,   nil,   nil,    28,    29,    30,   nil,    21,    22,    23,
   nil,    37,   nil,    33,    18,    49,    34,   nil,   nil,   nil,
    35,    36,   nil,   nil,   nil,   nil,   nil,    15,    14,    13,
    31,   nil,   nil,    28,    29,    30,   nil,    21,    22,    23,
   nil,    37,   nil,    33,    18,   nil,    34,   nil,   nil,   nil,
    35,    36,   nil,   nil,   nil,   nil,   nil,    15,    14,    13,
    31,   nil,   nil,    28,    29,    30,   nil,    21,    22,    23,
   nil,    37,   nil,    33,    18,   nil,    34,   nil,   nil,   nil,
    35,    36,   nil,   nil,   nil,   nil,   nil,    15,    14,    13,
    31,   nil,   nil,    28,    29,    30,   nil,    21,    22,    23,
    37,   nil,    33,   nil,    18,    34,    37,   nil,    33,    35,
    36,    34,   nil,   nil,   nil,    35,    36,    15,   nil,   nil,
   nil,    37,   nil,    33,   nil,   nil,    34,   nil,   nil,   nil,
    35,    36,   nil,   nil,   nil,   nil,   nil,   nil,    14,    13,
    31,   nil,   nil,    28,    29,    30,    49,    21,    22,    23,
   nil,    37,    49,    33,    18,   nil,    34,   nil,   nil,   nil,
    35,    36,   nil,   nil,   nil,   nil,   nil,    15,    14,    13,
    31,   nil,   nil,    28,    29,    30,   nil,    21,    22,    23,
    37,   nil,    33,   nil,    18,    34,    37,   nil,    33,    35,
    36,    34,   nil,   nil,   nil,    35,    36,    15,   nil,   nil,
   nil,   nil,   nil,    14,    13,    31,   nil,   nil,    28,    29,
    30,   nil,    21,    22,    23,    60,    61,    62,    63,    18,
   nil,   nil,   nil,   nil,   nil,    68,    49,    67,    60,    61,
    62,    63,    15,   nil,   nil,   nil,   nil,   nil,    68,   nil,
    67,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    74,
    69,    73,    72,    71,    70,   nil,    59,    66,    65,    64,
   nil,   nil,    74,    69,    73,    72,    71,    70,   nil,    92,
    66,    65,    64,    60,    61,    62,    63,   nil,   nil,   nil,
   nil,   nil,   nil,    68,   nil,    67,    60,    61,    62,    63,
   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,    67,   nil,
   nil,   nil,   nil,   116,   nil,   nil,   nil,    74,    69,    73,
    72,    71,    70,   nil,   nil,    66,    65,    64,   nil,   nil,
    74,    69,    73,    72,    71,    70,   nil,   nil,    66,    65,
    64,    60,    61,    62,    63,   nil,   nil,   nil,   nil,   nil,
   nil,    68,   nil,    67,    60,    61,    62,    63,   nil,   nil,
   nil,   nil,   nil,   nil,    68,   118,    67,   nil,   nil,   nil,
   nil,   nil,   nil,   119,   nil,    74,    69,    73,    72,    71,
    70,   nil,   nil,    66,    65,    64,   nil,   nil,    74,    69,
    73,    72,    71,    70,   nil,   nil,    66,    65,    64,    60,
    61,    62,    63,   nil,   120,   nil,   nil,   nil,   nil,    68,
   nil,    67,    60,    61,    62,    63,   nil,   nil,   nil,   nil,
   nil,   nil,    68,    60,    61,    62,    63,   nil,   nil,   nil,
   nil,   nil,   nil,    74,    69,    73,    72,    71,    70,   nil,
   nil,    66,    65,    64,   nil,   nil,    74,    69,    73,    72,
    71,    70,   nil,   nil,    66,    65,    64,    74,    69,    73,
    72,    71,    70,   nil,   nil,    66,    65,    64,    60,    61,
    62,    63,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    60,
    61,    62,    63,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    60,    61,    62,    63,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   -77,   -77,   -77,   -77,   -77,   -77,   nil,   nil,
    66,    65,    64,   -77,   -77,   -77,   -77,   -77,   -77,   nil,
   nil,    66,    65,    64,   -77,   -77,   -77,   -77,   -77,   -77,
   nil,   nil,    66,    65,    64,    60,    61,    62,    63,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    60,    61,    62,    63,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    60,    61,    62,
    63,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -77,
   -77,   -77,   -77,   -77,   -77,   nil,   nil,    66,    65,    64,
   -77,   -77,   -77,   -77,   -77,   -77,   nil,   nil,    66,    65,
    64,   -77,   -77,   -77,   -77,   -77,   -77,   nil,   nil,    66,
    65,    64,    60,    61,    62,    63,   nil,   nil,   nil,   nil,
   nil,   nil,    68,   nil,    67,   nil,   nil,   nil,    60,    61,
    62,    63,   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,
    67,   nil,   nil,   nil,   nil,   nil,    74,    69,    73,    72,
    71,    70,   nil,   131,    66,    65,    64,   147,   nil,   nil,
   nil,   nil,    74,    69,    73,    72,    71,    70,   nil,   nil,
    66,    65,    64,    60,    61,    62,    63,   nil,   nil,   nil,
   nil,   nil,   nil,    68,   nil,    67,    60,    61,    62,    63,
   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,    67,   nil,
   nil,   nil,   nil,   162,   nil,   nil,   nil,    74,    69,    73,
    72,    71,    70,   nil,   nil,    66,    65,    64,   nil,   nil,
    74,    69,    73,    72,    71,    70,   nil,   nil,    66,    65,
    64 ]

racc_action_check = [
   115,   115,   115,   115,    22,    15,    22,    14,    14,    22,
   115,    27,   115,    22,    22,    23,     0,    23,    14,    91,
    23,    95,   137,    95,    23,    23,    95,   137,    91,     1,
    95,    95,    51,     3,   115,   115,   115,   115,   115,   115,
    51,    15,   115,   115,   115,    57,     4,    27,     5,   115,
    22,    22,     6,    57,     7,     9,     7,    97,    97,     7,
    12,    23,    23,     7,     7,    39,    39,    95,    95,    89,
    89,     7,     7,     7,   128,   128,     7,     7,     7,    21,
     7,     7,     7,    25,    13,    29,    13,     7,    40,    13,
   139,   139,    41,    13,    13,   140,   140,    97,    97,    97,
     7,    13,    13,    13,    42,    43,    13,    13,    13,    46,
    13,    13,    13,    50,    16,    56,    16,    13,    78,    16,
    83,    84,    86,    16,    16,    88,    90,   113,   121,   122,
    13,    16,    16,    16,   124,   129,    16,    16,    16,   134,
    16,    16,    16,    18,   136,    18,   138,    16,    18,    28,
   141,    28,    18,    18,    28,   143,   146,   148,    28,    28,
    16,    30,   149,    30,   159,   160,    30,    31,   161,    31,
    30,    30,    31,    33,   163,    33,    31,    31,    33,   164,
   169,   170,    33,    33,    98,    98,   nil,   nil,    34,    18,
    34,   nil,   nil,    34,    60,    28,    60,    34,    34,    60,
    61,   nil,    61,    60,    60,    61,    62,    30,    62,    61,
    61,    62,    63,    31,    63,    62,    62,    63,    64,    33,
    64,    63,    63,    64,    98,    98,    98,    64,    64,   nil,
   nil,   nil,   nil,    65,    34,    65,   nil,   nil,    65,    66,
    60,    66,    65,    65,    66,    67,    61,    67,    66,    66,
    67,    68,    62,    68,    67,    67,    68,    69,    63,    69,
    68,    68,    69,    70,    64,    70,    69,    69,    70,   nil,
   nil,   nil,    70,    70,   nil,   nil,   nil,   nil,    71,    65,
    71,   nil,   nil,    71,    72,    66,    72,    71,    71,    72,
    73,    67,    73,    72,    72,    73,    74,    68,    74,    73,
    73,    74,    75,    69,    75,    74,    74,    75,    76,    70,
    76,    75,    75,    76,    76,   nil,   nil,    76,    76,   nil,
   nil,   nil,   nil,   nil,    71,   nil,   nil,   nil,   nil,   117,
    72,   117,   nil,   nil,   117,   nil,    73,   nil,   117,   117,
   nil,    87,    74,    87,   nil,   nil,    87,   nil,    75,   nil,
    87,    87,   nil,   nil,    76,   nil,   nil,   nil,    87,    87,
    87,   nil,   nil,    87,    87,    87,   nil,    87,    87,    87,
   nil,   116,   nil,   116,    87,   117,   116,   nil,   nil,   nil,
   116,   116,   nil,   nil,   nil,   nil,   nil,    87,   116,   116,
   116,   nil,   nil,   116,   116,   116,   nil,   116,   116,   116,
   nil,   118,   nil,   118,   116,   nil,   118,   nil,   nil,   nil,
   118,   118,   nil,   nil,   nil,   nil,   nil,   116,   118,   118,
   118,   nil,   nil,   118,   118,   118,   nil,   118,   118,   118,
   nil,   119,   nil,   119,   118,   nil,   119,   nil,   nil,   nil,
   119,   119,   nil,   nil,   nil,   nil,   nil,   118,   119,   119,
   119,   nil,   nil,   119,   119,   119,   nil,   119,   119,   119,
   133,   nil,   133,   nil,   119,   133,   147,   nil,   147,   133,
   133,   147,   nil,   nil,   nil,   147,   147,   119,   nil,   nil,
   nil,   150,   nil,   150,   nil,   nil,   150,   nil,   nil,   nil,
   150,   150,   nil,   nil,   nil,   nil,   nil,   nil,   150,   150,
   150,   nil,   nil,   150,   150,   150,   133,   150,   150,   150,
   nil,   151,   147,   151,   150,   nil,   151,   nil,   nil,   nil,
   151,   151,   nil,   nil,   nil,   nil,   nil,   150,   151,   151,
   151,   nil,   nil,   151,   151,   151,   nil,   151,   151,   151,
   162,   nil,   162,   nil,   151,   162,   165,   nil,   165,   162,
   162,   165,   nil,   nil,   nil,   165,   165,   151,   nil,   nil,
   nil,   nil,   nil,   165,   165,   165,   nil,   nil,   165,   165,
   165,   nil,   165,   165,   165,    26,    26,    26,    26,   165,
   nil,   nil,   nil,   nil,   nil,    26,   162,    26,    48,    48,
    48,    48,   165,   nil,   nil,   nil,   nil,   nil,    48,   nil,
    48,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    26,
    26,    26,    26,    26,    26,   nil,    26,    26,    26,    26,
   nil,   nil,    48,    48,    48,    48,    48,    48,   nil,    48,
    48,    48,    48,    52,    52,    52,    52,   nil,   nil,   nil,
   nil,   nil,   nil,    52,   nil,    52,    77,    77,    77,    77,
   nil,   nil,   nil,   nil,   nil,   nil,    77,   nil,    77,   nil,
   nil,   nil,   nil,    77,   nil,   nil,   nil,    52,    52,    52,
    52,    52,    52,   nil,   nil,    52,    52,    52,   nil,   nil,
    77,    77,    77,    77,    77,    77,   nil,   nil,    77,    77,
    77,    79,    79,    79,    79,   nil,   nil,   nil,   nil,   nil,
   nil,    79,   nil,    79,    80,    80,    80,    80,   nil,   nil,
   nil,   nil,   nil,   nil,    80,    79,    80,   nil,   nil,   nil,
   nil,   nil,   nil,    80,   nil,    79,    79,    79,    79,    79,
    79,   nil,   nil,    79,    79,    79,   nil,   nil,    80,    80,
    80,    80,    80,    80,   nil,   nil,    80,    80,    80,    82,
    82,    82,    82,   nil,    82,   nil,   nil,   nil,   nil,    82,
   nil,    82,   104,   104,   104,   104,   nil,   nil,   nil,   nil,
   nil,   nil,   104,   105,   105,   105,   105,   nil,   nil,   nil,
   nil,   nil,   nil,    82,    82,    82,    82,    82,    82,   nil,
   nil,    82,    82,    82,   nil,   nil,   104,   104,   104,   104,
   104,   104,   nil,   nil,   104,   104,   104,   105,   105,   105,
   105,   105,   105,   nil,   nil,   105,   105,   105,   106,   106,
   106,   106,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   107,
   107,   107,   107,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   108,   108,   108,   108,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   106,   106,   106,   106,   106,   106,   nil,   nil,
   106,   106,   106,   107,   107,   107,   107,   107,   107,   nil,
   nil,   107,   107,   107,   108,   108,   108,   108,   108,   108,
   nil,   nil,   108,   108,   108,   109,   109,   109,   109,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   110,   110,   110,   110,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   111,   111,   111,
   111,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   109,
   109,   109,   109,   109,   109,   nil,   nil,   109,   109,   109,
   110,   110,   110,   110,   110,   110,   nil,   nil,   110,   110,
   110,   111,   111,   111,   111,   111,   111,   nil,   nil,   111,
   111,   111,   112,   112,   112,   112,   nil,   nil,   nil,   nil,
   nil,   nil,   112,   nil,   112,   nil,   nil,   nil,   135,   135,
   135,   135,   nil,   nil,   nil,   nil,   nil,   nil,   135,   nil,
   135,   nil,   nil,   nil,   nil,   nil,   112,   112,   112,   112,
   112,   112,   nil,   112,   112,   112,   112,   135,   nil,   nil,
   nil,   nil,   135,   135,   135,   135,   135,   135,   nil,   nil,
   135,   135,   135,   156,   156,   156,   156,   nil,   nil,   nil,
   nil,   nil,   nil,   156,   nil,   156,   166,   166,   166,   166,
   nil,   nil,   nil,   nil,   nil,   nil,   166,   nil,   166,   nil,
   nil,   nil,   nil,   156,   nil,   nil,   nil,   156,   156,   156,
   156,   156,   156,   nil,   nil,   156,   156,   156,   nil,   nil,
   166,   166,   166,   166,   166,   166,   nil,   nil,   166,   166,
   166 ]

racc_action_pointer = [
   -18,    29,   nil,    17,    12,     0,    52,    52,   nil,    48,
   nil,   nil,    42,    82,    -2,    -2,   112,   nil,   141,   nil,
   nil,    31,     2,    13,   nil,    39,   572,     4,   147,    37,
   159,   165,   nil,   171,   186,   nil,   nil,   nil,   nil,    56,
    44,    74,    84,    87,   nil,   nil,    61,   nil,   585,   nil,
    69,   -12,   630,   nil,   nil,   nil,   108,     1,   nil,   nil,
   192,   198,   204,   210,   216,   231,   237,   243,   249,   255,
   261,   276,   282,   288,   294,   300,   306,   643,    87,   688,
   701,   nil,   746,   112,    73,   nil,    78,   339,    81,    60,
    82,   -24,   nil,   nil,   nil,    19,   nil,    52,   179,   nil,
   nil,   nil,   nil,   nil,   759,   770,   815,   826,   837,   882,
   893,   904,   949,   119,   nil,    -3,   369,   327,   399,   429,
   nil,    92,    77,   nil,   116,   nil,   nil,   nil,    65,    87,
   nil,   nil,   nil,   458,   121,   965,   126,     4,   129,    81,
    86,   106,   nil,   103,   nil,   nil,   112,   464,   113,   118,
   479,   509,   nil,   nil,   nil,   nil,  1010,   nil,   nil,   146,
   147,   148,   538,   130,   135,   544,  1023,   nil,   nil,   162,
   137,   nil ]

racc_action_default = [
    -3,   -77,    -1,   -77,    -3,   -77,   -77,   -77,    -4,   -77,
   -12,   172,   -77,   -77,   -77,   -75,   -25,   -27,   -77,   -29,
   -30,   -77,   -77,   -77,   -34,   -77,   -77,   -77,   -77,   -77,
   -77,   -77,   -54,   -77,   -77,   -72,   -73,   -74,   -76,    -9,
   -77,   -77,   -77,   -77,   -13,   -14,   -77,   -26,   -77,   -75,
   -77,   -77,   -37,   -38,   -39,   -41,   -77,   -77,   -35,   -36,
   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,
   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,   -77,
   -77,   -62,   -77,   -77,   -77,    -2,   -77,   -23,   -77,   -15,
   -77,   -19,   -28,   -31,   -32,   -77,   -33,   -55,   -56,   -57,
   -58,   -59,   -60,   -61,   -64,   -65,   -66,   -67,   -68,   -69,
   -70,   -71,   -77,   -77,   -51,   -52,   -77,   -77,   -77,   -77,
   -63,   -21,   -10,    -6,   -77,   -24,    -8,   -16,   -17,   -77,
   -40,   -42,   -50,   -77,   -77,   -77,   -77,   -77,   -77,   -77,
    -9,   -77,   -18,   -19,   -20,   -53,   -77,   -77,   -77,   -77,
   -77,   -23,   -22,   -11,    -7,   -43,   -46,   -45,   -48,   -77,
   -77,   -77,   -77,   -77,   -77,   -77,   -47,   -49,    -5,   -77,
   -77,   -44 ]

racc_goto_table = [
    12,    42,    83,    48,    84,    90,    41,    52,    52,    47,
   124,    51,    57,    77,   113,    79,    80,     1,    81,    82,
    54,    54,     3,     2,   138,    89,     8,   161,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    97,    98,    99,   100,   101,
   102,   103,   104,   105,   106,   107,   108,   109,   110,   111,
   112,   115,   nil,   nil,   nil,     9,   nil,   nil,   nil,   nil,
   nil,   145,   nil,   nil,   160,   nil,   127,   nil,   nil,   nil,
    52,    50,    56,    56,   130,   nil,   nil,   nil,   144,    78,
   nil,   nil,   nil,    54,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   135,   153,   152,    84,    91,   nil,   nil,   134,
   nil,   136,   137,   nil,   nil,   142,   nil,   nil,   115,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   156,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   159,   122,   nil,   nil,   166,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    56,   nil,   nil,   169,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   143 ]

racc_goto_check = [
     4,    11,     7,    16,    12,    14,     4,    16,    16,     4,
     9,    18,    18,    16,    23,    16,    16,     1,    16,    16,
    20,    20,     3,     2,     8,    13,     3,    22,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    16,    16,    16,    16,    16,
    16,    16,    16,    16,    16,    16,    16,    16,    16,    16,
    16,    16,   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,
   nil,    23,   nil,   nil,     9,   nil,    11,   nil,   nil,   nil,
    16,     6,     6,     6,    18,   nil,   nil,   nil,    14,     6,
   nil,   nil,   nil,    20,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    16,     7,    12,    12,     6,   nil,   nil,     4,
   nil,     4,     4,   nil,   nil,    11,   nil,   nil,    16,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    16,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     4,     6,   nil,   nil,    16,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     6,   nil,   nil,     4,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6 ]

racc_goto_pointer = [
   nil,    17,    23,    22,    -7,   nil,    60,   -37,   -97,   -77,
   nil,   -13,   -35,   -21,   -41,   nil,   -15,   nil,   -11,   nil,
    -2,   nil,  -129,   -62,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   125,     4,    27,   nil,   nil,   nil,
    17,   nil,    46,    19,   nil,    16,    26,    20,   nil,    24,
    25,    53,   nil,   nil,    32,    38 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 55, :_reduce_1,
  5, 56, :_reduce_2,
  0, 57, :_reduce_none,
  2, 57, :_reduce_4,
  10, 59, :_reduce_5,
  4, 64, :_reduce_6,
  6, 64, :_reduce_7,
  4, 64, :_reduce_8,
  0, 61, :_reduce_none,
  2, 61, :_reduce_10,
  4, 61, :_reduce_11,
  1, 60, :_reduce_12,
  1, 66, :_reduce_13,
  1, 66, :_reduce_14,
  2, 65, :_reduce_15,
  3, 65, :_reduce_16,
  3, 65, :_reduce_17,
  4, 65, :_reduce_18,
  1, 68, :_reduce_19,
  3, 68, :_reduce_20,
  0, 62, :_reduce_none,
  2, 62, :_reduce_22,
  0, 63, :_reduce_none,
  1, 63, :_reduce_none,
  1, 58, :_reduce_25,
  2, 58, :_reduce_26,
  1, 69, :_reduce_27,
  3, 69, :_reduce_28,
  1, 69, :_reduce_29,
  1, 69, :_reduce_30,
  3, 69, :_reduce_31,
  3, 69, :_reduce_32,
  3, 69, :_reduce_33,
  1, 69, :_reduce_34,
  2, 69, :_reduce_35,
  2, 69, :_reduce_36,
  1, 72, :_reduce_37,
  1, 72, :_reduce_38,
  1, 72, :_reduce_39,
  3, 72, :_reduce_40,
  1, 75, :_reduce_41,
  4, 67, :_reduce_42,
  6, 71, :_reduce_43,
  11, 71, :_reduce_44,
  6, 71, :_reduce_45,
  0, 76, :_reduce_none,
  2, 76, :_reduce_47,
  6, 73, :_reduce_48,
  8, 73, :_reduce_49,
  4, 74, :_reduce_50,
  3, 74, :_reduce_51,
  1, 77, :_reduce_52,
  3, 77, :_reduce_53,
  1, 70, :_reduce_none,
  3, 70, :_reduce_55,
  3, 70, :_reduce_56,
  3, 70, :_reduce_57,
  3, 70, :_reduce_58,
  3, 70, :_reduce_59,
  3, 70, :_reduce_60,
  3, 70, :_reduce_61,
  2, 70, :_reduce_62,
  3, 70, :_reduce_63,
  3, 70, :_reduce_64,
  3, 70, :_reduce_65,
  3, 70, :_reduce_66,
  3, 70, :_reduce_67,
  3, 70, :_reduce_68,
  3, 70, :_reduce_69,
  3, 70, :_reduce_70,
  3, 70, :_reduce_71,
  1, 79, :_reduce_72,
  1, 79, :_reduce_73,
  1, 78, :_reduce_74,
  1, 78, :_reduce_75,
  1, 78, :_reduce_none ]

racc_reduce_n = 77

racc_shift_n = 172

racc_token_table = {
  false => 0,
  :error => 1,
  :DIGIT => 2,
  :PLUS => 3,
  :LESS => 4,
  :MULT => 5,
  :DIV2 => 6,
  :LPARENT => 7,
  :RPARENT => 8,
  :TYPEN => 9,
  :TYPEB => 10,
  :TRUE => 11,
  :FALSE => 12,
  :AND => 13,
  :NOT => 14,
  :OR => 15,
  :PROGRAM => 16,
  :BEGIN => 17,
  :END => 18,
  :WITH => 19,
  :DO => 20,
  :IF => 21,
  :THEN => 22,
  :ELSE => 23,
  :WHILE => 24,
  :FOR => 25,
  :REPEAT => 26,
  :TIMES => 27,
  :READ => 28,
  :WRITE => 29,
  :WRITELN => 30,
  :FROM => 31,
  :TO => 32,
  :BY => 33,
  :FUNC => 34,
  :RETURN => 35,
  :RETURN2 => 36,
  :EQUIVALENT => 37,
  :LESSTHAN => 38,
  :DISTINCT => 39,
  :GETHAN => 40,
  :LETHAN => 41,
  :GREATTHAN => 42,
  :EQUAL => 43,
  :SEMICOLON => 44,
  :MOD => 45,
  :DIV => 46,
  :MOD2 => 47,
  :ID => 48,
  :STRING => 49,
  :LCURLY => 50,
  :RCURLY => 51,
  :COLON => 52,
  :UMINUS => 53 }

racc_nt_base = 54

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DIGIT",
  "PLUS",
  "LESS",
  "MULT",
  "DIV2",
  "LPARENT",
  "RPARENT",
  "TYPEN",
  "TYPEB",
  "TRUE",
  "FALSE",
  "AND",
  "NOT",
  "OR",
  "PROGRAM",
  "BEGIN",
  "END",
  "WITH",
  "DO",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "FOR",
  "REPEAT",
  "TIMES",
  "READ",
  "WRITE",
  "WRITELN",
  "FROM",
  "TO",
  "BY",
  "FUNC",
  "RETURN",
  "RETURN2",
  "EQUIVALENT",
  "LESSTHAN",
  "DISTINCT",
  "GETHAN",
  "LETHAN",
  "GREATTHAN",
  "EQUAL",
  "SEMICOLON",
  "MOD",
  "DIV",
  "MOD2",
  "ID",
  "STRING",
  "LCURLY",
  "RCURLY",
  "COLON",
  "UMINUS",
  "$start",
  "S",
  "Scope",
  "Listfunciones",
  "LInst",
  "funciones",
  "Var",
  "ListD",
  "Retorno",
  "funcInst",
  "wis",
  "Ldecl",
  "type",
  "Assign",
  "ListID",
  "Inst",
  "Expr",
  "Iterator",
  "writable",
  "Cond",
  "Call",
  "Str",
  "by",
  "ListParam",
  "Term",
  "Bool" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'retina_parser.y', 43)
  def _reduce_1(val, _values, result)
    result = S.new(val[0]);result.printAST(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 48)
  def _reduce_2(val, _values, result)
    result = Scope.new(:Funciones,val[0],:Program,val[2])
    result
  end
.,.,

# reduce 3 omitted

module_eval(<<'.,.,', 'retina_parser.y', 53)
  def _reduce_4(val, _values, result)
    result=ListaFunc.new(:Funcion,val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 57)
  def _reduce_5(val, _values, result)
    result=Func.new(:Nombre_Funcion,val[1],:Parametros,val[3],:Tipo_Retorno,val[5],:Instrucciones,val[7])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 61)
  def _reduce_6(val, _values, result)
    result=Bloque.new(:declaraciones,nil,:instrucciones,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 62)
  def _reduce_7(val, _values, result)
    result=Bloque.new(:declaraciones,val[1],:instrucciones,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 63)
  def _reduce_8(val, _values, result)
    result=Bloque.new(:declaraciones,nil,:instrucciones,nil)
    result
  end
.,.,

# reduce 9 omitted

module_eval(<<'.,.,', 'retina_parser.y', 68)
  def _reduce_10(val, _values, result)
    result=ListD.new(:tipos,val[0],:identificadores,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 69)
  def _reduce_11(val, _values, result)
    result=List.new(:tipos,val[0],val[3],:identificadores,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 73)
  def _reduce_12(val, _values, result)
    result = Terms.new(:ID , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 77)
  def _reduce_13(val, _values, result)
    result=Type.new(:Tipo,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 78)
  def _reduce_14(val, _values, result)
    result=Type.new(:Tipo,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 82)
  def _reduce_15(val, _values, result)
    result=Ldecl.new(:declaracion,:tipo,val[0],:asignacion,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 83)
  def _reduce_16(val, _values, result)
    result=Ldecl.new(:declaracion,:tipo,val[0],:asignacion,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 84)
  def _reduce_17(val, _values, result)
    result=Ldecl.new(:declaracion,:tipo,val[0],:Lista_ID,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 85)
  def _reduce_18(val, _values, result)
    result=Ldecl.new(:Lista_Decl,:tipo,val[0],:Lista_ID,val[1],:declaracion,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 89)
  def _reduce_19(val, _values, result)
    result=ListaInst.new(:ID,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 90)
  def _reduce_20(val, _values, result)
    result=ListaInst.new(:ID,val[0],val[2])
    result
  end
.,.,

# reduce 21 omitted

module_eval(<<'.,.,', 'retina_parser.y', 95)
  def _reduce_22(val, _values, result)
    result=Bloque.new(:tipo,val[1])
    result
  end
.,.,

# reduce 23 omitted

# reduce 24 omitted

module_eval(<<'.,.,', 'retina_parser.y', 104)
  def _reduce_25(val, _values, result)
    result=ListaInst.new(:Instruccion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 105)
  def _reduce_26(val, _values, result)
    result=ListaInst.new(:Instruccion,val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 108)
  def _reduce_27(val, _values, result)
    result=Bloque.new(:Bloque,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 109)
  def _reduce_28(val, _values, result)
    result=Bloque.new(:Retorno,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 110)
  def _reduce_29(val, _values, result)
    result=Bloque.new(:Asignacion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 111)
  def _reduce_30(val, _values, result)
    result=Bloque.new(:Iteracion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 112)
  def _reduce_31(val, _values, result)
    result=Bloque.new(:Lectura,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 113)
  def _reduce_32(val, _values, result)
    result=Write.new(:Salida,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 114)
  def _reduce_33(val, _values, result)
    result=Write.new(:Salida_Con_Salto,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 115)
  def _reduce_34(val, _values, result)
    result=Bloque.new(:Condicional,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 116)
  def _reduce_35(val, _values, result)
    result=Bloque.new(:Llamada_de_Funcion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 117)
  def _reduce_36(val, _values, result)
    result=Bloque.new(:Expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 121)
  def _reduce_37(val, _values, result)
    result=Bloque.new(:expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 122)
  def _reduce_38(val, _values, result)
    result=Bloque.new(:string,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 123)
  def _reduce_39(val, _values, result)
    result=Bloque.new(:Call,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 124)
  def _reduce_40(val, _values, result)
    result=Bloque.new(:valor,val[0],:valor,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 128)
  def _reduce_41(val, _values, result)
    result=Str.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 132)
  def _reduce_42(val, _values, result)
    result=Assign.new(:Lado_Izquierdo,val[0],:Lado_Derecho,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 136)
  def _reduce_43(val, _values, result)
    result=WLoop.new(:Ciclo_While,:Condicion,val[1],:Do,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 137)
  def _reduce_44(val, _values, result)
    result= FLoop.new(:Ciclo_For,:For,val[1],:From,val[3],:To,val[5],:By,nil,:Instrucciones,val[8])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 138)
  def _reduce_45(val, _values, result)
    result=RLoop.new(:Ciclo_Repeat,:Times,val[1],:Instrucciones,val[3])
    result
  end
.,.,

# reduce 46 omitted

module_eval(<<'.,.,', 'retina_parser.y', 143)
  def _reduce_47(val, _values, result)
    result=Bloque.new(:By,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 147)
  def _reduce_48(val, _values, result)
    result=Cond.new(:Condición,val[1],:Instrucciones,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 148)
  def _reduce_49(val, _values, result)
    result=Cond.new(:Condicion,val[1],:Instrucciones,val[3],:Instrucciones_Else,val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 152)
  def _reduce_50(val, _values, result)
    result=Call.new(:nombre,val[0],:argumentos,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 153)
  def _reduce_51(val, _values, result)
    result=Call.new(:nombre,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 157)
  def _reduce_52(val, _values, result)
    result=Bloque.new(:expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 158)
  def _reduce_53(val, _values, result)
    result=Bloque.new(:expresion,val[0])
    result
  end
.,.,

# reduce 54 omitted

module_eval(<<'.,.,', 'retina_parser.y', 168)
  def _reduce_55(val, _values, result)
    result = BinExp.new(:Suma, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 169)
  def _reduce_56(val, _values, result)
    result = BinExp.new(:Resta, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 170)
  def _reduce_57(val, _values, result)
    result = BinExp.new(:Multiplicacion, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 171)
  def _reduce_58(val, _values, result)
    result = BinExp.new(:Division_Exacta, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 172)
  def _reduce_59(val, _values, result)
    result = BinExp.new(:Resto_Exacto, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 173)
  def _reduce_60(val, _values, result)
    result = BinExp.new(:Division_Entera, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 174)
  def _reduce_61(val, _values, result)
    result = BinExp.new(:Resto_Entero, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 175)
  def _reduce_62(val, _values, result)
    result = UnaExp.new(:Inverso_Aditivo , val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 176)
  def _reduce_63(val, _values, result)
    result = ParExp.new(:Expresion, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 177)
  def _reduce_64(val, _values, result)
    result = BinExp.new(:Or , val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 178)
  def _reduce_65(val, _values, result)
    result = BinExp.new(:And, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 179)
  def _reduce_66(val, _values, result)
    result = BinExp.new(:Menor_que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 180)
  def _reduce_67(val, _values, result)
    result = BinExp.new(:Mayor_que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 181)
  def _reduce_68(val, _values, result)
    result = BinExp.new(:Menor_O_Igual_Que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 182)
  def _reduce_69(val, _values, result)
    result = BinExp.new(:Mayor_O_Igual_Que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 183)
  def _reduce_70(val, _values, result)
    result = BinExp.new(:Distinto_Que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 184)
  def _reduce_71(val, _values, result)
    result = BinExp.new(:Equivalencia,val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 190)
  def _reduce_72(val, _values, result)
    result = Terms.new(:TRUE , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 191)
  def _reduce_73(val, _values, result)
    result = Terms.new(:FALSE , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 195)
  def _reduce_74(val, _values, result)
    result= Terms.new(:DIGIT,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 196)
  def _reduce_75(val, _values, result)
    result = Terms.new(:ID , val[0])
    result
  end
.,.,

# reduce 76 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
