#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative "retina_lexer"

require_relative 'retina_ast'

class SyntacticError < RuntimeError

    def initialize(tok)
        @token = tok
    end

    def to_s
        if @token.eql? "$" then
            "Unexpected EOF"
        else
           " Línea #{@token.position[0]}, Column #{@token.position[1]}: token inesperado : #{@token.symbol} : #{@token.id}"
        end
    end
end

class Parser < Racc::Parser

module_eval(<<'...end retina_parser.y/module_eval...', 'retina_parser.y', 232)


def on_error(id, token, stack)
    raise SyntacticError::new(token)
end

def initialize(lexer)
  @lexer=lexer
end

def next_token
    if ((token = @lexer.next_token)!=nil)
        return [token.symbol,token]
    else 
        return nil
    end

end


def parse(lexer)
	@yydebug = true
	@lexer = lexer
	@tokens = []
	do_parse
	
end
...end retina_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    61,    62,    63,    64,    38,   -12,    33,    45,    46,    35,
    69,    77,    68,    36,    37,    38,    34,    33,    44,    76,
    35,    38,     5,    33,    36,    37,    35,    34,   133,     6,
    36,    37,    96,    34,    75,    70,    74,    73,    72,    71,
    97,   -12,    67,    66,    65,    98,     7,    76,     5,   137,
    15,    56,    10,    97,    38,   153,    33,    63,    64,    35,
   154,    15,    56,    36,    37,    11,    34,    15,    56,    45,
    46,    14,    13,    31,    45,    46,    28,    29,    30,    40,
    21,    22,    23,    41,    38,    10,    33,    18,    59,    35,
    45,    46,    10,    36,    37,    87,    34,    67,    66,    65,
    15,    14,    13,    31,    45,    46,    28,    29,    30,    88,
    21,    22,    23,    89,    38,    90,    33,    18,    10,    35,
    45,    46,    95,    36,    37,    77,    34,   121,   125,    10,
    15,    14,    13,    31,   127,   130,    28,    29,    30,   132,
    21,    22,    23,    38,   135,    33,   136,    18,    35,    38,
   143,    33,    36,    37,    35,    34,   144,   145,    36,    37,
    15,    34,    38,    10,    33,   150,   152,    35,    38,   155,
    33,    36,    37,    35,    34,   158,   133,    36,    37,   159,
    34,    38,   161,    33,   162,   167,    35,   168,   169,    50,
    36,    37,    38,    34,    33,    50,   171,    35,   172,   174,
   175,    36,    37,   nil,    34,   nil,   nil,    38,    50,    33,
   nil,   nil,    35,    38,    50,    33,    36,    37,    35,    34,
   nil,   nil,    36,    37,    38,    34,    33,    50,   nil,    35,
    38,   nil,    33,    36,    37,    35,    34,   nil,    50,    36,
    37,   nil,    34,   nil,   nil,    38,   nil,    33,   nil,   nil,
    35,   nil,   nil,    50,    36,    37,    38,    34,    33,    50,
   nil,    35,    38,   nil,    33,    36,    37,    35,    34,   nil,
    50,    36,    37,    38,    34,    33,    50,   nil,    35,   nil,
   nil,   nil,    36,    37,    38,    34,    33,   nil,   nil,    35,
   nil,    50,   nil,    36,    37,    38,    34,    33,   nil,   nil,
    35,    38,    50,    33,    36,    37,    35,    34,    50,   nil,
    36,    37,    38,    34,    33,   nil,   nil,    35,   nil,    50,
   nil,    36,    37,    38,    34,    33,   nil,   nil,    35,   nil,
    50,   nil,    36,    37,    38,    34,    33,   nil,   nil,    35,
    38,    50,    33,    36,    37,    35,    34,    50,   nil,    36,
    37,    38,    34,    33,   nil,   nil,    35,   nil,    50,   nil,
    36,    37,    38,    34,    33,   nil,   nil,    35,   nil,    50,
   nil,    36,    37,    38,    34,    33,   nil,   nil,    35,   118,
    50,   nil,    36,    37,   nil,    34,    50,   nil,   nil,   nil,
    63,    64,   nil,   nil,    38,   nil,    33,    50,   nil,    35,
   nil,   nil,   nil,    36,    37,   nil,    34,   nil,    15,   nil,
   nil,    14,    13,    31,   nil,   nil,    28,    29,    30,    50,
    21,    22,    23,   nil,    38,   nil,    33,    18,   nil,    35,
    67,    66,    65,    36,    37,   nil,    34,   nil,   nil,   nil,
    15,    14,    13,    31,   nil,   nil,    28,    29,    30,   nil,
    21,    22,    23,    38,   nil,    33,   nil,    18,    35,    38,
   nil,    33,    36,    37,    35,    34,   nil,   nil,    36,    37,
    15,    34,   nil,   nil,   nil,   nil,    14,    13,    31,   nil,
   nil,    28,    29,    30,   nil,    21,    22,    23,   nil,   nil,
   nil,    38,    18,    33,   nil,   nil,    35,   nil,   nil,    50,
    36,    37,   nil,    34,   nil,    15,   nil,   nil,    14,    13,
    31,   nil,   nil,    28,    29,    30,   nil,    21,    22,    23,
    38,   nil,    33,   nil,    18,    35,    38,   nil,    33,    36,
    37,    35,    34,   nil,   nil,    36,    37,    15,    34,   nil,
   nil,    38,   nil,    33,   nil,   nil,    35,   nil,   nil,   nil,
    36,    37,   nil,    34,   nil,   nil,   nil,   nil,    14,    13,
    31,   nil,   nil,    28,    29,    30,    50,    21,    22,    23,
   nil,    38,    50,    33,    18,   nil,    35,   nil,   nil,   nil,
    36,    37,   nil,    34,   nil,   nil,   nil,    15,    14,    13,
    31,   nil,   nil,    28,    29,    30,   nil,    21,    22,    23,
    38,   nil,    33,   nil,    18,    35,    38,   nil,    33,    36,
    37,    35,    34,   nil,   nil,    36,    37,    15,    34,   nil,
   nil,   nil,   nil,    14,    13,    31,   nil,   nil,    28,    29,
    30,   nil,    21,    22,    23,    61,    62,    63,    64,    18,
   nil,   nil,   nil,   nil,   nil,    69,    50,    68,    61,    62,
    63,    64,    15,   nil,   nil,   nil,   nil,   nil,    69,   nil,
    68,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    75,
    70,    74,    73,    72,    71,   nil,    60,    67,    66,    65,
   nil,   nil,    75,    70,    74,    73,    72,    71,   nil,    94,
    67,    66,    65,    61,    62,    63,    64,   nil,   nil,   nil,
   nil,   nil,   nil,    69,   nil,    68,    61,    62,    63,    64,
   nil,   nil,   nil,   nil,   nil,   nil,    69,   nil,    68,   nil,
   nil,   nil,   nil,   120,   nil,   nil,   nil,    75,    70,    74,
    73,    72,    71,   nil,   nil,    67,    66,    65,   nil,   nil,
    75,    70,    74,    73,    72,    71,   nil,   nil,    67,    66,
    65,    61,    62,    63,    64,   nil,   nil,   nil,   nil,   nil,
   nil,    69,   nil,    68,    61,    62,    63,    64,   nil,   nil,
   nil,   nil,   nil,   nil,    69,   122,    68,   nil,   nil,   nil,
   nil,   nil,   nil,   123,   nil,    75,    70,    74,    73,    72,
    71,   nil,   nil,    67,    66,    65,   nil,   nil,    75,    70,
    74,    73,    72,    71,   nil,   nil,    67,    66,    65,    61,
    62,    63,    64,   nil,   124,   nil,   nil,   nil,   nil,    69,
   nil,    68,    61,    62,    63,    64,   nil,   nil,   nil,   nil,
   nil,   nil,    69,    61,    62,    63,    64,   nil,   nil,   nil,
   nil,   nil,   nil,    75,    70,    74,    73,    72,    71,   nil,
   nil,    67,    66,    65,   nil,   nil,    75,    70,    74,    73,
    72,    71,   nil,   nil,    67,    66,    65,    75,    70,    74,
    73,    72,    71,   nil,   nil,    67,    66,    65,    61,    62,
    63,    64,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    61,
    62,    63,    64,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    61,    62,    63,    64,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   -80,   -80,   -80,   -80,   -80,   -80,   nil,   nil,
    67,    66,    65,   -80,   -80,   -80,   -80,   -80,   -80,   nil,
   nil,    67,    66,    65,   -80,   -80,   -80,   -80,   -80,   -80,
   nil,   nil,    67,    66,    65,    61,    62,    63,    64,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    61,    62,    63,    64,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    61,    62,    63,
    64,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -80,
   -80,   -80,   -80,   -80,   -80,   nil,   nil,    67,    66,    65,
   -80,   -80,   -80,   -80,   -80,   -80,   nil,   nil,    67,    66,
    65,   -80,   -80,   -80,   -80,   -80,   -80,   nil,   nil,    67,
    66,    65,    61,    62,    63,    64,   nil,   nil,   nil,   nil,
   nil,   nil,    69,   nil,    68,   nil,   nil,   nil,    61,    62,
    63,    64,   nil,   nil,   nil,   nil,   nil,   nil,    69,   nil,
    68,   nil,   nil,   nil,   nil,   nil,    75,    70,    74,    73,
    72,    71,   nil,   nil,    67,    66,    65,   151,   nil,   nil,
   nil,   nil,    75,    70,    74,    73,    72,    71,   nil,   nil,
    67,    66,    65,    61,    62,    63,    64,   nil,   nil,   nil,
   nil,   nil,   nil,    69,   nil,    68,    61,    62,    63,    64,
   nil,   nil,   nil,   nil,   nil,   nil,    69,   nil,    68,   nil,
   nil,   nil,   nil,   166,   nil,   nil,   nil,    75,    70,    74,
    73,    72,    71,   nil,   nil,    67,    66,    65,   nil,   nil,
    75,    70,    74,    73,    72,    71,   nil,   nil,    67,    66,
    65 ]

racc_action_check = [
   119,   119,   119,   119,    22,    15,    22,    14,    14,    22,
   119,    27,   119,    22,    22,    23,    22,    23,    14,    93,
    23,    97,     0,    97,    23,    23,    97,    23,    93,     1,
    97,    97,    52,    97,   119,   119,   119,   119,   119,   119,
    52,    15,   119,   119,   119,    58,     3,    27,     4,   119,
    22,    22,     5,    58,     7,   141,     7,    99,    99,     7,
   141,    23,    23,     7,     7,     6,     7,    97,    97,    40,
    40,     7,     7,     7,    91,    91,     7,     7,     7,     9,
     7,     7,     7,    12,    13,    21,    13,     7,    25,    13,
   132,   132,    29,    13,    13,    41,    13,    99,    99,    99,
     7,    13,    13,    13,   143,   143,    13,    13,    13,    42,
    13,    13,    13,    43,    16,    44,    16,    13,    47,    16,
   144,   144,    51,    16,    16,    57,    16,    79,    85,    86,
    13,    16,    16,    16,    88,    90,    16,    16,    16,    92,
    16,    16,    16,    18,   114,    18,   117,    16,    18,    28,
   125,    28,    18,    18,    28,    18,   126,   128,    28,    28,
    16,    28,    30,   133,    30,   138,   140,    30,    31,   142,
    31,    30,    30,    31,    30,   145,   147,    31,    31,   150,
    31,    33,   152,    33,   153,   163,    33,   164,   165,    18,
    33,    33,    34,    33,    34,    28,   167,    34,   168,   173,
   174,    34,    34,   nil,    34,   nil,   nil,    35,    30,    35,
   nil,   nil,    35,    61,    31,    61,    35,    35,    61,    35,
   nil,   nil,    61,    61,    62,    61,    62,    33,   nil,    62,
    63,   nil,    63,    62,    62,    63,    62,   nil,    34,    63,
    63,   nil,    63,   nil,   nil,    64,   nil,    64,   nil,   nil,
    64,   nil,   nil,    35,    64,    64,    65,    64,    65,    61,
   nil,    65,    66,   nil,    66,    65,    65,    66,    65,   nil,
    62,    66,    66,    67,    66,    67,    63,   nil,    67,   nil,
   nil,   nil,    67,    67,    68,    67,    68,   nil,   nil,    68,
   nil,    64,   nil,    68,    68,    69,    68,    69,   nil,   nil,
    69,    70,    65,    70,    69,    69,    70,    69,    66,   nil,
    70,    70,    71,    70,    71,   nil,   nil,    71,   nil,    67,
   nil,    71,    71,    72,    71,    72,   nil,   nil,    72,   nil,
    68,   nil,    72,    72,    73,    72,    73,   nil,   nil,    73,
    74,    69,    74,    73,    73,    74,    73,    70,   nil,    74,
    74,    75,    74,    75,   nil,   nil,    75,   nil,    71,   nil,
    75,    75,    76,    75,    76,   nil,   nil,    76,   nil,    72,
   nil,    76,    76,    77,    76,    77,   nil,   nil,    77,    77,
    73,   nil,    77,    77,   nil,    77,    74,   nil,   nil,   nil,
   100,   100,   nil,   nil,    89,   nil,    89,    75,   nil,    89,
   nil,   nil,   nil,    89,    89,   nil,    89,   nil,    76,   nil,
   nil,    89,    89,    89,   nil,   nil,    89,    89,    89,    77,
    89,    89,    89,   nil,   120,   nil,   120,    89,   nil,   120,
   100,   100,   100,   120,   120,   nil,   120,   nil,   nil,   nil,
    89,   120,   120,   120,   nil,   nil,   120,   120,   120,   nil,
   120,   120,   120,   121,   nil,   121,   nil,   120,   121,   122,
   nil,   122,   121,   121,   122,   121,   nil,   nil,   122,   122,
   120,   122,   nil,   nil,   nil,   nil,   122,   122,   122,   nil,
   nil,   122,   122,   122,   nil,   122,   122,   122,   nil,   nil,
   nil,   123,   122,   123,   nil,   nil,   123,   nil,   nil,   121,
   123,   123,   nil,   123,   nil,   122,   nil,   nil,   123,   123,
   123,   nil,   nil,   123,   123,   123,   nil,   123,   123,   123,
   137,   nil,   137,   nil,   123,   137,   151,   nil,   151,   137,
   137,   151,   137,   nil,   nil,   151,   151,   123,   151,   nil,
   nil,   154,   nil,   154,   nil,   nil,   154,   nil,   nil,   nil,
   154,   154,   nil,   154,   nil,   nil,   nil,   nil,   154,   154,
   154,   nil,   nil,   154,   154,   154,   137,   154,   154,   154,
   nil,   155,   151,   155,   154,   nil,   155,   nil,   nil,   nil,
   155,   155,   nil,   155,   nil,   nil,   nil,   154,   155,   155,
   155,   nil,   nil,   155,   155,   155,   nil,   155,   155,   155,
   166,   nil,   166,   nil,   155,   166,   169,   nil,   169,   166,
   166,   169,   166,   nil,   nil,   169,   169,   155,   169,   nil,
   nil,   nil,   nil,   169,   169,   169,   nil,   nil,   169,   169,
   169,   nil,   169,   169,   169,    26,    26,    26,    26,   169,
   nil,   nil,   nil,   nil,   nil,    26,   166,    26,    49,    49,
    49,    49,   169,   nil,   nil,   nil,   nil,   nil,    49,   nil,
    49,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    26,
    26,    26,    26,    26,    26,   nil,    26,    26,    26,    26,
   nil,   nil,    49,    49,    49,    49,    49,    49,   nil,    49,
    49,    49,    49,    53,    53,    53,    53,   nil,   nil,   nil,
   nil,   nil,   nil,    53,   nil,    53,    78,    78,    78,    78,
   nil,   nil,   nil,   nil,   nil,   nil,    78,   nil,    78,   nil,
   nil,   nil,   nil,    78,   nil,   nil,   nil,    53,    53,    53,
    53,    53,    53,   nil,   nil,    53,    53,    53,   nil,   nil,
    78,    78,    78,    78,    78,    78,   nil,   nil,    78,    78,
    78,    80,    80,    80,    80,   nil,   nil,   nil,   nil,   nil,
   nil,    80,   nil,    80,    81,    81,    81,    81,   nil,   nil,
   nil,   nil,   nil,   nil,    81,    80,    81,   nil,   nil,   nil,
   nil,   nil,   nil,    81,   nil,    80,    80,    80,    80,    80,
    80,   nil,   nil,    80,    80,    80,   nil,   nil,    81,    81,
    81,    81,    81,    81,   nil,   nil,    81,    81,    81,    84,
    84,    84,    84,   nil,    84,   nil,   nil,   nil,   nil,    84,
   nil,    84,   106,   106,   106,   106,   nil,   nil,   nil,   nil,
   nil,   nil,   106,   107,   107,   107,   107,   nil,   nil,   nil,
   nil,   nil,   nil,    84,    84,    84,    84,    84,    84,   nil,
   nil,    84,    84,    84,   nil,   nil,   106,   106,   106,   106,
   106,   106,   nil,   nil,   106,   106,   106,   107,   107,   107,
   107,   107,   107,   nil,   nil,   107,   107,   107,   108,   108,
   108,   108,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   109,
   109,   109,   109,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   110,   110,   110,   110,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   108,   108,   108,   108,   108,   108,   nil,   nil,
   108,   108,   108,   109,   109,   109,   109,   109,   109,   nil,
   nil,   109,   109,   109,   110,   110,   110,   110,   110,   110,
   nil,   nil,   110,   110,   110,   111,   111,   111,   111,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   112,   112,   112,   112,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   113,   113,   113,
   113,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   111,
   111,   111,   111,   111,   111,   nil,   nil,   111,   111,   111,
   112,   112,   112,   112,   112,   112,   nil,   nil,   112,   112,
   112,   113,   113,   113,   113,   113,   113,   nil,   nil,   113,
   113,   113,   115,   115,   115,   115,   nil,   nil,   nil,   nil,
   nil,   nil,   115,   nil,   115,   nil,   nil,   nil,   139,   139,
   139,   139,   nil,   nil,   nil,   nil,   nil,   nil,   139,   nil,
   139,   nil,   nil,   nil,   nil,   nil,   115,   115,   115,   115,
   115,   115,   nil,   nil,   115,   115,   115,   139,   nil,   nil,
   nil,   nil,   139,   139,   139,   139,   139,   139,   nil,   nil,
   139,   139,   139,   160,   160,   160,   160,   nil,   nil,   nil,
   nil,   nil,   nil,   160,   nil,   160,   170,   170,   170,   170,
   nil,   nil,   nil,   nil,   nil,   nil,   170,   nil,   170,   nil,
   nil,   nil,   nil,   160,   nil,   nil,   nil,   160,   160,   160,
   160,   160,   160,   nil,   nil,   160,   160,   160,   nil,   nil,
   170,   170,   170,   170,   170,   170,   nil,   nil,   170,   170,
   170 ]

racc_action_pointer = [
   -12,    29,   nil,    30,    14,     4,    65,    52,   nil,    72,
   nil,   nil,    65,    82,    -2,    -2,   112,   nil,   141,   nil,
   nil,    37,     2,    13,   nil,    44,   632,     4,   147,    44,
   160,   166,   nil,   179,   190,   205,   nil,   nil,   nil,   nil,
    60,    51,    91,    93,    97,   nil,   nil,    70,   nil,   645,
   nil,    78,   -12,   690,   nil,   nil,   nil,   118,     1,   nil,
   nil,   211,   222,   228,   243,   254,   260,   271,   282,   293,
   299,   310,   321,   332,   338,   349,   360,   371,   703,    96,
   748,   761,   nil,   nil,   806,   120,    81,   nil,    90,   392,
    91,    65,    95,   -24,   nil,   nil,   nil,    19,   nil,    52,
   385,   nil,   nil,   nil,   nil,   nil,   819,   830,   875,   886,
   897,   942,   953,   964,   100,  1009,   nil,   138,   nil,    -3,
   422,   451,   457,   489,   nil,   114,   104,   nil,   139,   nil,
   nil,   nil,    81,   115,   nil,   nil,   nil,   518,   147,  1025,
   148,    37,   152,    95,   111,   131,   nil,   124,   nil,   nil,
   135,   524,   138,   140,   539,   569,   nil,   nil,   nil,   nil,
  1070,   nil,   nil,   167,   169,   168,   598,   152,   154,   604,
  1083,   nil,   nil,   181,   156,   nil ]

racc_action_default = [
    -3,   -80,    -1,   -80,    -3,   -80,   -80,   -80,    -4,   -80,
   -12,   176,   -80,   -80,   -80,   -78,   -25,   -27,   -80,   -29,
   -30,   -80,   -80,   -80,   -34,   -80,   -80,   -80,   -80,   -80,
   -80,   -80,   -56,   -80,   -80,   -80,   -75,   -76,   -77,   -79,
    -9,   -80,   -80,   -80,   -80,   -13,   -14,   -80,   -26,   -80,
   -78,   -80,   -80,   -37,   -38,   -39,   -41,   -80,   -80,   -35,
   -36,   -80,   -80,   -80,   -80,   -80,   -80,   -80,   -80,   -80,
   -80,   -80,   -80,   -80,   -80,   -80,   -80,   -80,   -80,   -80,
   -80,   -80,   -64,   -65,   -80,   -80,   -80,    -2,   -80,   -23,
   -80,   -15,   -80,   -19,   -28,   -31,   -32,   -80,   -33,   -57,
   -58,   -59,   -60,   -61,   -62,   -63,   -67,   -68,   -69,   -70,
   -71,   -72,   -73,   -74,   -80,   -43,   -44,   -80,   -53,   -54,
   -80,   -80,   -80,   -80,   -66,   -21,   -10,    -6,   -80,   -24,
    -8,   -16,   -17,   -80,   -40,   -42,   -52,   -80,   -80,   -80,
   -80,   -80,   -80,   -80,    -9,   -80,   -18,   -19,   -20,   -55,
   -80,   -80,   -80,   -80,   -80,   -23,   -22,   -11,    -7,   -45,
   -48,   -47,   -50,   -80,   -80,   -80,   -80,   -80,   -80,   -80,
   -49,   -51,    -5,   -80,   -80,   -46 ]

racc_goto_table = [
    12,    43,    92,    49,    85,   128,    42,    53,    53,    48,
    52,    58,   117,    78,    86,    80,    81,     1,    82,    83,
    84,    55,    55,     3,     2,   142,    91,     8,   114,   165,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    99,   100,   101,   102,
   103,   104,   105,   106,   107,   108,   109,   110,   111,   112,
   113,   115,   119,     9,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   164,   149,   nil,   nil,   116,   nil,   nil,   131,    51,
    57,    57,    53,   nil,   nil,   134,   nil,    79,   148,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    55,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    93,   139,   nil,   157,   nil,
   nil,   nil,   nil,   138,   nil,   140,   141,   156,    86,   146,
   nil,   nil,   119,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    57,   nil,   160,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   126,   nil,   nil,   163,   nil,   nil,
   nil,   170,   nil,   nil,   nil,    57,   nil,   nil,   nil,   nil,
   nil,   nil,   173,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   147 ]

racc_goto_check = [
     4,    11,    14,    16,     7,     9,     4,    16,    16,     4,
    18,    18,    24,    16,    12,    16,    16,     1,    16,    16,
    16,    20,    20,     3,     2,     8,    13,     3,    22,    23,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    16,    16,    16,    16,
    16,    16,    16,    16,    16,    16,    16,    16,    16,    16,
    16,    16,    16,     6,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     9,    24,   nil,   nil,    20,   nil,   nil,    11,     6,
     6,     6,    16,   nil,   nil,    18,   nil,     6,    14,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    20,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     6,    16,   nil,     7,   nil,
   nil,   nil,   nil,     4,   nil,     4,     4,    12,    12,    11,
   nil,   nil,    16,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     6,   nil,    16,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     6,   nil,   nil,     4,   nil,   nil,
   nil,    16,   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,
   nil,   nil,     4,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     6 ]

racc_goto_pointer = [
   nil,    17,    24,    23,    -7,   nil,    58,   -36,  -100,   -84,
   nil,   -13,   -26,   -21,   -45,   nil,   -15,   nil,   -12,   nil,
    -1,   nil,   -48,  -131,   -65,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   129,     4,    27,   nil,   nil,   nil,
    17,   nil,    47,    19,   nil,    16,    26,    20,   nil,    24,
    25,    54,   nil,   nil,   nil,    32,    39 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 55, :_reduce_1,
  5, 56, :_reduce_2,
  0, 57, :_reduce_none,
  2, 57, :_reduce_4,
  10, 59, :_reduce_5,
  4, 64, :_reduce_6,
  6, 64, :_reduce_7,
  4, 64, :_reduce_8,
  0, 61, :_reduce_none,
  2, 61, :_reduce_10,
  4, 61, :_reduce_11,
  1, 60, :_reduce_12,
  1, 66, :_reduce_13,
  1, 66, :_reduce_14,
  2, 65, :_reduce_15,
  3, 65, :_reduce_16,
  3, 65, :_reduce_17,
  4, 65, :_reduce_18,
  1, 68, :_reduce_19,
  3, 68, :_reduce_20,
  0, 62, :_reduce_none,
  2, 62, :_reduce_22,
  0, 63, :_reduce_none,
  1, 63, :_reduce_none,
  1, 58, :_reduce_25,
  2, 58, :_reduce_26,
  1, 69, :_reduce_27,
  3, 69, :_reduce_28,
  1, 69, :_reduce_29,
  1, 69, :_reduce_30,
  3, 69, :_reduce_31,
  3, 69, :_reduce_32,
  3, 69, :_reduce_33,
  1, 69, :_reduce_34,
  2, 69, :_reduce_35,
  2, 69, :_reduce_36,
  1, 72, :_reduce_37,
  1, 72, :_reduce_38,
  1, 72, :_reduce_39,
  3, 72, :_reduce_40,
  1, 75, :_reduce_41,
  4, 67, :_reduce_42,
  1, 76, :_reduce_43,
  1, 76, :_reduce_44,
  6, 71, :_reduce_45,
  11, 71, :_reduce_46,
  6, 71, :_reduce_47,
  0, 77, :_reduce_none,
  2, 77, :_reduce_49,
  6, 73, :_reduce_50,
  8, 73, :_reduce_51,
  4, 74, :_reduce_52,
  3, 74, :_reduce_53,
  1, 78, :_reduce_54,
  3, 78, :_reduce_55,
  1, 70, :_reduce_none,
  3, 70, :_reduce_57,
  3, 70, :_reduce_58,
  3, 70, :_reduce_59,
  3, 70, :_reduce_60,
  3, 70, :_reduce_61,
  3, 70, :_reduce_62,
  3, 70, :_reduce_63,
  2, 70, :_reduce_64,
  2, 70, :_reduce_65,
  3, 70, :_reduce_66,
  3, 70, :_reduce_67,
  3, 70, :_reduce_68,
  3, 70, :_reduce_69,
  3, 70, :_reduce_70,
  3, 70, :_reduce_71,
  3, 70, :_reduce_72,
  3, 70, :_reduce_73,
  3, 70, :_reduce_74,
  1, 80, :_reduce_75,
  1, 80, :_reduce_76,
  1, 79, :_reduce_77,
  1, 79, :_reduce_78,
  1, 79, :_reduce_none ]

racc_reduce_n = 80

racc_shift_n = 176

racc_token_table = {
  false => 0,
  :error => 1,
  :DIGIT => 2,
  :PLUS => 3,
  :LESS => 4,
  :MULT => 5,
  :DIV2 => 6,
  :LPARENT => 7,
  :RPARENT => 8,
  :TYPEN => 9,
  :TYPEB => 10,
  :TRUE => 11,
  :FALSE => 12,
  :AND => 13,
  :NOT => 14,
  :OR => 15,
  :PROGRAM => 16,
  :BEGIN => 17,
  :END => 18,
  :WITH => 19,
  :DO => 20,
  :IF => 21,
  :THEN => 22,
  :ELSE => 23,
  :WHILE => 24,
  :FOR => 25,
  :REPEAT => 26,
  :TIMES => 27,
  :READ => 28,
  :WRITE => 29,
  :WRITELN => 30,
  :FROM => 31,
  :TO => 32,
  :BY => 33,
  :FUNC => 34,
  :RETURN => 35,
  :RETURN2 => 36,
  :EQUIVALENT => 37,
  :LESSTHAN => 38,
  :DISTINCT => 39,
  :GETHAN => 40,
  :LETHAN => 41,
  :GREATTHAN => 42,
  :EQUAL => 43,
  :SEMICOLON => 44,
  :MOD => 45,
  :DIV => 46,
  :MOD2 => 47,
  :ID => 48,
  :STRING => 49,
  :LCURLY => 50,
  :RCURLY => 51,
  :COLON => 52,
  :UMINUS => 53 }

racc_nt_base = 54

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DIGIT",
  "PLUS",
  "LESS",
  "MULT",
  "DIV2",
  "LPARENT",
  "RPARENT",
  "TYPEN",
  "TYPEB",
  "TRUE",
  "FALSE",
  "AND",
  "NOT",
  "OR",
  "PROGRAM",
  "BEGIN",
  "END",
  "WITH",
  "DO",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "FOR",
  "REPEAT",
  "TIMES",
  "READ",
  "WRITE",
  "WRITELN",
  "FROM",
  "TO",
  "BY",
  "FUNC",
  "RETURN",
  "RETURN2",
  "EQUIVALENT",
  "LESSTHAN",
  "DISTINCT",
  "GETHAN",
  "LETHAN",
  "GREATTHAN",
  "EQUAL",
  "SEMICOLON",
  "MOD",
  "DIV",
  "MOD2",
  "ID",
  "STRING",
  "LCURLY",
  "RCURLY",
  "COLON",
  "UMINUS",
  "$start",
  "S",
  "Scope",
  "Listfunciones",
  "LInst",
  "funciones",
  "Var",
  "ListD",
  "Retorno",
  "funcInst",
  "wis",
  "Ldecl",
  "type",
  "Assign",
  "ListID",
  "Inst",
  "Expr",
  "Iterator",
  "writable",
  "Cond",
  "Call",
  "Str",
  "Asignable",
  "by",
  "ListParam",
  "Term",
  "Bool" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'retina_parser.y', 43)
  def _reduce_1(val, _values, result)
    result = S.new(val[0]);result.printAST(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 48)
  def _reduce_2(val, _values, result)
    result = Scope.new(:Funciones,val[0],:Program,val[2])
    result
  end
.,.,

# reduce 3 omitted

module_eval(<<'.,.,', 'retina_parser.y', 53)
  def _reduce_4(val, _values, result)
    result=ListaFunc.new(:Funcion,val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 57)
  def _reduce_5(val, _values, result)
    result=Func.new(:Nombre_Funcion,val[1],:Parametros,val[3],:Tipo_Retorno,val[5],:Instrucciones,val[7])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 61)
  def _reduce_6(val, _values, result)
    result=Bloque.new(:declaraciones,nil,:instrucciones,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 62)
  def _reduce_7(val, _values, result)
    result=Bloque.new(:declaraciones,val[1],:instrucciones,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 63)
  def _reduce_8(val, _values, result)
    result=Bloque.new(:declaraciones,nil,:instrucciones,nil)
    result
  end
.,.,

# reduce 9 omitted

module_eval(<<'.,.,', 'retina_parser.y', 68)
  def _reduce_10(val, _values, result)
    result=ListD.new(:tipos,val[0],:identificadores,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 69)
  def _reduce_11(val, _values, result)
    result=List.new(:tipos,val[0],val[3],:identificadores,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 73)
  def _reduce_12(val, _values, result)
    result = Terms.new(:ID , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 77)
  def _reduce_13(val, _values, result)
    result=Type.new(:Tipo,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 78)
  def _reduce_14(val, _values, result)
    result=Type.new(:Tipo,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 82)
  def _reduce_15(val, _values, result)
    result=Ldecl.new(:declaracion,:tipo,val[0],:asignacion,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 83)
  def _reduce_16(val, _values, result)
    result=Ldecl.new(:declaracion,:tipo,val[0],:asignacion,val[1],:declaracion,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 84)
  def _reduce_17(val, _values, result)
    result=Ldecl.new(:declaracion,:tipo,val[0],:Lista_ID,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 85)
  def _reduce_18(val, _values, result)
    result=Ldecl.new(:Lista_Decl,:tipo,val[0],:Lista_ID,val[1],:declaracion,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 89)
  def _reduce_19(val, _values, result)
    result=ListID.new(:ID,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 90)
  def _reduce_20(val, _values, result)
    result=ListID.new(:ID,val[0],val[2])
    result
  end
.,.,

# reduce 21 omitted

module_eval(<<'.,.,', 'retina_parser.y', 95)
  def _reduce_22(val, _values, result)
    result=Retorno.new(:tipo,val[1])
    result
  end
.,.,

# reduce 23 omitted

# reduce 24 omitted

module_eval(<<'.,.,', 'retina_parser.y', 104)
  def _reduce_25(val, _values, result)
    result=ListaInst.new(:Instruccion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 105)
  def _reduce_26(val, _values, result)
    result=ListaInst.new(:Instruccion,val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 108)
  def _reduce_27(val, _values, result)
    result=Inst.new(:Bloque,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 109)
  def _reduce_28(val, _values, result)
    result=Inst.new(:Retorno,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 110)
  def _reduce_29(val, _values, result)
    result=Inst.new(:Asignacion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 111)
  def _reduce_30(val, _values, result)
    result=Inst.new(:Iteracion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 112)
  def _reduce_31(val, _values, result)
    result=Inst.new(:Lectura,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 113)
  def _reduce_32(val, _values, result)
    result=Write.new(:Salida,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 114)
  def _reduce_33(val, _values, result)
    result=Write.new(:Salida_Con_Salto,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 115)
  def _reduce_34(val, _values, result)
    result=Inst.new(:Condicional,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 116)
  def _reduce_35(val, _values, result)
    result=Inst.new(:Llamada_de_Funcion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 117)
  def _reduce_36(val, _values, result)
    result=Inst.new(:Expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 121)
  def _reduce_37(val, _values, result)
    result=Writable.new(:Expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 122)
  def _reduce_38(val, _values, result)
    result=Writable.new(:String,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 123)
  def _reduce_39(val, _values, result)
    result=Writable.new(:Llamada_de_Funcion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 124)
  def _reduce_40(val, _values, result)
    result=Writable.new(:valor,val[0],:valor,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 128)
  def _reduce_41(val, _values, result)
    result=Str.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 132)
  def _reduce_42(val, _values, result)
    result=Assign.new(:Lado_Izquierdo,val[0],:Lado_Derecho,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 136)
  def _reduce_43(val, _values, result)
    result=Asignable.new(:Expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 137)
  def _reduce_44(val, _values, result)
    result=Asignable.new(:Llamada_de_Funcion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 141)
  def _reduce_45(val, _values, result)
    result=WLoop.new(:Ciclo_While,:Condicion,val[1],:Do,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 142)
  def _reduce_46(val, _values, result)
    result= FLoop.new(:Ciclo_For,:For,val[1],:From,val[3],:To,val[5],:By,val[6],:Instrucciones,val[8])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 143)
  def _reduce_47(val, _values, result)
    result=RLoop.new(:Ciclo_Repeat,:Times,val[1],:Instrucciones,val[3])
    result
  end
.,.,

# reduce 48 omitted

module_eval(<<'.,.,', 'retina_parser.y', 148)
  def _reduce_49(val, _values, result)
    result=By.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 152)
  def _reduce_50(val, _values, result)
    result=Cond.new(:Condición,val[1],:Instrucciones,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 153)
  def _reduce_51(val, _values, result)
    result=Cond.new(:Condicion,val[1],:Instrucciones,val[3],:Instrucciones_Else,val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 157)
  def _reduce_52(val, _values, result)
    result=Call.new(:nombre,val[0],:argumentos,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 158)
  def _reduce_53(val, _values, result)
    result=Call.new(:nombre,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 162)
  def _reduce_54(val, _values, result)
    result=ListParam.new(:expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 163)
  def _reduce_55(val, _values, result)
    result=ListParam.new(:expresion,val[0],val[2])
    result
  end
.,.,

# reduce 56 omitted

module_eval(<<'.,.,', 'retina_parser.y', 173)
  def _reduce_57(val, _values, result)
    result = BinExp.new(:Suma, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 174)
  def _reduce_58(val, _values, result)
    result = BinExp.new(:Resta, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 175)
  def _reduce_59(val, _values, result)
    result = BinExp.new(:Multiplicacion, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 176)
  def _reduce_60(val, _values, result)
    result = BinExp.new(:Division_Exacta, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 177)
  def _reduce_61(val, _values, result)
    result = BinExp.new(:Resto_Exacto, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 178)
  def _reduce_62(val, _values, result)
    result = BinExp.new(:Division_Entera, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 179)
  def _reduce_63(val, _values, result)
    result = BinExp.new(:Resto_Entero, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 180)
  def _reduce_64(val, _values, result)
    result = UnaExp.new(:Inverso_Aditivo , val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 181)
  def _reduce_65(val, _values, result)
    result = UnaExp.new(:Negacion , val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 182)
  def _reduce_66(val, _values, result)
    result = ParExp.new(:Expresion, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 183)
  def _reduce_67(val, _values, result)
    result = BinExp.new(:Or , val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 184)
  def _reduce_68(val, _values, result)
    result = BinExp.new(:And, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 185)
  def _reduce_69(val, _values, result)
    result = BinExp.new(:Menor_que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 186)
  def _reduce_70(val, _values, result)
    result = BinExp.new(:Mayor_que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 187)
  def _reduce_71(val, _values, result)
    result = BinExp.new(:Menor_O_Igual_Que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 188)
  def _reduce_72(val, _values, result)
    result = BinExp.new(:Mayor_O_Igual_Que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 189)
  def _reduce_73(val, _values, result)
    result = BinExp.new(:Distinto_Que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 190)
  def _reduce_74(val, _values, result)
    result = BinExp.new(:Equivalencia,val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 196)
  def _reduce_75(val, _values, result)
    result = Terms.new(:TRUE , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 197)
  def _reduce_76(val, _values, result)
    result = Terms.new(:FALSE , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 201)
  def _reduce_77(val, _values, result)
    result= Terms.new(:DIGIT,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 202)
  def _reduce_78(val, _values, result)
    result = Terms.new(:ID , val[0])
    result
  end
.,.,

# reduce 79 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
