#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative "retina_lexer"

require_relative 'retina_ast'

class SyntacticError < RuntimeError

    def initialize(tok)
        @token = tok
    end

    def to_s
        if @token.eql? "$" then
            "Unexpected EOF"
        else
            case @token.symbol
                when :TYPEN,:TYPEB
                tokenName="tipo de dato"
            when :TRUE,:FALSE
                tokenName="literal booleano"
            when :AND,:NOT,:OR
                tokenName="operador booleano"
            when :PROGRAM,:BEGIN,:END,:WITH,:DO,:IF,:THEN,:READ,:ELSE,:WHILE,:FOR,:REPEAT,:WRITE,:WRITELN,:FROM,:TO,:BY,:FUNC,:RETURN,:RETURN2
                tokenName="palabra reservada"
            when :EQUIVALENT,:LESSTHAN,:DISTINCT,:GETHAN,:LESSTHAN,:GREATTHAN
                tokenName="operador de comparación"
            when :LPARENT,:RPARENT,:EQUAL,:SEMICOLON,:COLON,:RCURLY,:LCURLY
                tokenName="signo"
            when :PLUS,:MOD,:DIV,:MOD2,:DIV2,:MULT,:LESS
                tokenName="operador aritmético"
            when :ID
                tokenName="identificador"
            when :STRING
                tokenName="string"
            when :DIGIT
                tokenName="literal numérico"
            end
           return " Línea #{@token.position[0]}, Column #{@token.position[1]}: token inesperado : "<< tokenName << " : #{@token.id}"
        end
    end
end

class Parser < Racc::Parser

module_eval(<<'...end retina_parser.y/module_eval...', 'retina_parser.y', 308)


def on_error(id, token, stack)
    raise SyntacticError::new(token)
end

def initialize(lexer)
  @lexer=lexer
end

def next_token
    if ((token = @lexer.next_token)!=nil)
        return [token.symbol,token]
    else 
        return nil
    end

end


def parse(lexer)
	@yydebug = true
	@lexer = lexer
	@tokens = []
	do_parse
	
end
...end retina_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    60,    61,    62,    63,    38,   -18,    33,    47,    48,    35,
    68,    76,    67,    36,    37,    38,    34,    33,    46,    75,
    35,    38,     5,    33,    36,    37,    35,    34,   133,   166,
    36,    37,    95,    34,    74,    69,    73,    72,    71,    70,
    96,   -18,    66,    65,    64,    47,    48,    75,   163,   138,
    16,    54,    62,    63,    38,   157,    33,   213,   133,    35,
   158,    16,    54,    36,    37,    98,    34,    16,    54,    38,
   162,    33,    62,    63,    35,    38,   188,    33,    36,    37,
    35,    34,   212,   189,    36,    37,    38,    34,    33,   159,
    96,    35,    66,    65,    64,    36,    37,    38,    34,    33,
    16,    54,    35,    97,   156,   231,    36,    37,   154,    34,
   232,    98,    66,    65,    64,    16,    54,    10,    38,    10,
    33,    16,    54,    35,    47,    48,   149,    36,    37,   148,
    34,   146,    16,   145,    41,    15,    14,    30,    47,    48,
    27,    28,    29,    16,    21,    22,    23,    10,    38,   192,
    33,    47,    48,    35,    47,    48,   137,    36,    37,   136,
    34,    47,    48,   203,    16,   170,   169,   185,   132,   205,
   182,   183,   184,   206,   177,   178,   179,   129,    38,   208,
    33,   174,   209,    35,   126,   211,    10,    36,    37,   124,
    34,   120,   215,   165,    16,    15,    14,    30,    76,    94,
    27,    28,    29,    10,    21,    22,    23,   219,    38,    88,
    33,   221,    86,    35,    10,    10,    43,    36,    37,   226,
    34,   227,   228,    40,    16,   170,   169,   185,   230,    11,
   182,   183,   184,   233,   177,   178,   179,   234,    38,   235,
    33,   174,    10,    35,   237,   238,     5,    36,    37,     7,
    34,   241,   242,   243,    16,    15,    14,    30,     6,   245,
    27,    28,    29,   246,    21,    22,    23,   nil,    38,   nil,
    33,   nil,   nil,    35,   nil,   nil,   nil,    36,    37,   nil,
    34,   nil,   nil,   nil,    16,   170,   169,   185,   nil,   nil,
   182,   183,   184,   nil,   177,   178,   179,   nil,   nil,   nil,
    38,   174,    33,   nil,   nil,    35,   nil,   nil,   nil,    36,
    37,   nil,    34,   nil,    16,   nil,    13,    15,    14,    30,
   nil,   nil,    27,    28,    29,   nil,    21,    22,    23,    38,
   nil,    33,   nil,   nil,    35,    38,   nil,    33,    36,    37,
    35,    34,   nil,   nil,    36,    37,    16,    34,    38,   nil,
    33,   nil,   nil,    35,    38,   nil,    33,    36,    37,    35,
    34,   nil,   nil,    36,    37,   nil,    34,    38,   nil,    33,
   nil,   nil,    35,   nil,   nil,    16,    36,    37,    38,    34,
    33,    16,   nil,    35,   nil,   nil,   nil,    36,    37,   nil,
    34,   nil,   nil,    38,    16,    33,   nil,   nil,    35,    38,
    16,    33,    36,    37,    35,    34,   nil,   nil,    36,    37,
    38,    34,    33,    16,   nil,    35,   nil,   nil,   nil,    36,
    37,   nil,    34,   nil,    16,    38,   nil,    33,   nil,   nil,
    35,   nil,   nil,   nil,    36,    37,   nil,    34,   nil,    16,
   nil,   nil,   170,   169,   185,    16,   nil,   182,   183,   184,
   nil,   177,   178,   179,   nil,    38,    16,    33,   174,   nil,
    35,   nil,   nil,   nil,    36,    37,   nil,    34,   nil,   nil,
   nil,    16,   170,   169,   185,   nil,   nil,   182,   183,   184,
   nil,   177,   178,   179,   nil,   nil,   nil,    38,   174,    33,
   nil,   nil,    35,   nil,   nil,   nil,    36,    37,   nil,    34,
   nil,    16,   nil,    87,    15,    14,    30,   nil,   nil,    27,
    28,    29,   nil,    21,    22,    23,   nil,    38,   nil,    33,
   nil,   nil,    35,   nil,   nil,   nil,    36,    37,   nil,    34,
   nil,   nil,   nil,    16,   170,   169,   185,   nil,   nil,   182,
   183,   184,   nil,   177,   178,   179,   nil,   nil,   nil,    38,
   174,    33,   nil,   nil,    35,   nil,   nil,   nil,    36,    37,
   nil,    34,   nil,    16,   nil,    89,    15,    14,    30,   nil,
   nil,    27,    28,    29,   nil,    21,    22,    23,    38,   nil,
    33,   nil,   nil,    35,    38,   nil,    33,    36,    37,    35,
    34,   nil,   nil,    36,    37,    16,    34,   nil,   nil,   nil,
   nil,    15,    14,    30,   nil,   nil,    27,    28,    29,   nil,
    21,    22,    23,   nil,   nil,   nil,    38,   nil,    33,   nil,
   nil,    35,   nil,   nil,    16,    36,    37,   nil,    34,   nil,
    16,   nil,   147,    15,    14,    30,   nil,   nil,    27,    28,
    29,   nil,    21,    22,    23,    38,   nil,    33,   nil,   nil,
    35,    38,   nil,    33,    36,    37,    35,    34,   nil,   nil,
    36,    37,    16,    34,   nil,   nil,   nil,   nil,    15,    14,
    30,   nil,   nil,    27,    28,    29,   nil,    21,    22,    23,
   nil,   nil,   nil,    38,   nil,    33,   nil,   nil,    35,   nil,
   nil,    16,    36,    37,   nil,    34,   nil,    16,   nil,   nil,
    15,    14,    30,   nil,   nil,    27,    28,    29,   nil,    21,
    22,    23,    38,   nil,    33,   nil,   nil,    35,    38,   nil,
    33,    36,    37,    35,    34,   nil,   nil,    36,    37,    16,
    34,    38,   nil,    33,   nil,   nil,    35,    38,   nil,    33,
    36,    37,    35,    34,   nil,   nil,    36,    37,   nil,    34,
    38,   nil,    33,   nil,   nil,    35,   nil,   nil,    16,    36,
    37,    38,    34,    33,    16,   nil,    35,   nil,   nil,   nil,
    36,    37,   nil,    34,   nil,   nil,    38,    16,    33,   nil,
   nil,    35,   nil,    16,   nil,    36,    37,   nil,    34,   nil,
   nil,   nil,   nil,    15,    14,    30,    16,   nil,    27,    28,
    29,   nil,    21,    22,    23,   nil,    38,    16,    33,   nil,
   nil,    35,   nil,   nil,   nil,    36,    37,   nil,    34,    38,
   nil,    33,    16,   nil,    35,    38,   nil,    33,    36,    37,
    35,    34,   nil,   nil,    36,    37,    38,    34,    33,   nil,
   nil,    35,   nil,   nil,   nil,    36,    37,   nil,    34,   nil,
   nil,   nil,    16,   170,   169,   185,   nil,   nil,   182,   183,
   184,   nil,   177,   178,   179,    16,   nil,   nil,    38,   174,
    33,    16,   nil,    35,    38,   nil,    33,    36,    37,    35,
    34,   nil,    16,    36,    37,    38,    34,    33,   nil,   nil,
    35,    38,   nil,    33,    36,    37,    35,    34,   nil,   nil,
    36,    37,   nil,    34,   nil,   nil,    38,   nil,    33,   nil,
   nil,    35,   nil,   nil,    16,    36,    37,    38,    34,    33,
    16,   nil,    35,   nil,   nil,   nil,    36,    37,   nil,    34,
    38,    16,    33,   nil,   nil,    35,   117,    16,   nil,    36,
    37,    38,    34,    33,   nil,   nil,    35,   nil,   nil,   nil,
    36,    37,    16,    34,   nil,    38,   nil,    33,   nil,   nil,
    35,   nil,   nil,    16,    36,    37,   nil,    34,   nil,   nil,
   nil,   nil,   170,   169,   185,   nil,    16,   182,   183,   184,
   nil,   177,   178,   179,    38,   nil,    33,    16,   174,    35,
    38,   nil,    33,    36,    37,    35,    34,   nil,   nil,    36,
    37,    16,    34,   nil,   nil,   nil,   207,   170,   169,   185,
   nil,   nil,   182,   183,   184,   nil,   177,   178,   179,   nil,
   nil,   nil,    38,   174,    33,   nil,   nil,    35,   nil,   nil,
    16,    36,    37,   nil,    34,   nil,    16,   nil,   nil,    15,
    14,    30,   nil,   nil,    27,    28,    29,   nil,    21,    22,
    23,   nil,    38,   nil,    33,   nil,   nil,    35,   nil,   nil,
   nil,    36,    37,   nil,    34,   nil,   nil,   nil,    16,   170,
   169,   185,   nil,   nil,   182,   183,   184,   nil,   177,   178,
   179,    38,   nil,    33,   nil,   174,    35,    38,   nil,    33,
    36,    37,    35,    34,   nil,   nil,    36,    37,    16,    34,
   nil,   nil,   nil,   130,    15,    14,    30,   nil,   nil,    27,
    28,    29,   nil,    21,    22,    23,   nil,   nil,   nil,    38,
   nil,    33,   nil,   nil,    35,   nil,   nil,    16,    36,    37,
   nil,    34,   nil,    16,   nil,   128,    15,    14,    30,   nil,
   nil,    27,    28,    29,   nil,    21,    22,    23,    38,   nil,
    33,   nil,   nil,    35,   nil,   nil,   nil,    36,    37,   nil,
    34,    60,    61,    62,    63,    16,   nil,   nil,   nil,   nil,
   nil,    68,   nil,    67,   nil,   nil,    60,    61,    62,    63,
   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,    67,   nil,
   nil,   nil,   nil,   nil,    16,    74,    69,    73,    72,    71,
    70,   nil,   210,    66,    65,    64,   187,   nil,   nil,   nil,
    74,    69,    73,    72,    71,    70,   nil,   nil,    66,    65,
    64,    60,    61,    62,    63,   nil,   nil,   nil,   nil,   nil,
   nil,    68,   nil,    67,   nil,   nil,   nil,    60,    61,    62,
    63,   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,    67,
   nil,   187,   nil,   nil,   nil,    74,    69,    73,    72,    71,
    70,   nil,   nil,    66,    65,    64,   229,   nil,   nil,   nil,
   nil,    74,    69,    73,    72,    71,    70,   nil,   nil,    66,
    65,    64,    60,    61,    62,    63,   nil,   nil,   nil,   nil,
   nil,   nil,    68,   nil,    67,    60,    61,    62,    63,   nil,
   123,   nil,   nil,   nil,   nil,    68,   nil,    67,   nil,   nil,
   nil,   155,   nil,   nil,   nil,   nil,    74,    69,    73,    72,
    71,    70,   nil,   nil,    66,    65,    64,   nil,   nil,    74,
    69,    73,    72,    71,    70,   nil,   nil,    66,    65,    64,
    60,    61,    62,    63,   nil,   nil,   nil,   nil,   nil,   nil,
    68,   nil,    67,    60,    61,    62,    63,   nil,   nil,   nil,
   nil,   nil,   nil,    68,   nil,    67,   nil,   nil,   nil,   nil,
    60,    61,    62,    63,    74,    69,    73,    72,    71,    70,
    68,    59,    66,    65,    64,   nil,   nil,    74,    69,    73,
    72,    71,    70,   nil,   nil,    66,    65,    64,    60,    61,
    62,    63,   nil,   nil,    74,    69,    73,    72,    71,    70,
   nil,   nil,    66,    65,    64,    60,    61,    62,    63,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    60,    61,    62,    63,
   nil,   nil,    74,    69,    73,    72,    71,    70,   nil,   nil,
    66,    65,    64,    60,    61,    62,    63,   nil,   nil,  -104,
  -104,  -104,  -104,  -104,  -104,   nil,   nil,    66,    65,    64,
  -104,  -104,  -104,  -104,  -104,  -104,   nil,   nil,    66,    65,
    64,    60,    61,    62,    63,   nil,   nil,  -104,  -104,  -104,
  -104,  -104,  -104,   nil,   nil,    66,    65,    64,    60,    61,
    62,    63,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    60,
    61,    62,    63,   nil,   nil,  -104,  -104,  -104,  -104,  -104,
  -104,   nil,   nil,    66,    65,    64,   nil,   nil,   nil,   nil,
   nil,   nil,  -104,  -104,  -104,  -104,  -104,  -104,   nil,   nil,
    66,    65,    64,  -104,  -104,  -104,  -104,  -104,  -104,   nil,
   nil,    66,    65,    64,    60,    61,    62,    63,   nil,   nil,
   nil,   nil,   nil,   nil,    68,   nil,    67,   nil,   nil,   nil,
   nil,   nil,   nil,   122,   nil,    60,    61,    62,    63,   nil,
   nil,   nil,   nil,   nil,   nil,    68,   nil,    67,    74,    69,
    73,    72,    71,    70,   nil,   nil,    66,    65,    64,   121,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    74,
    69,    73,    72,    71,    70,   nil,   nil,    66,    65,    64,
    60,    61,    62,    63,   nil,   nil,   nil,   nil,   nil,   nil,
    68,   nil,    67,    60,    61,    62,    63,   214,   nil,   nil,
   nil,   nil,   nil,    68,   nil,    67,   nil,   nil,   nil,   nil,
   119,   nil,   nil,   nil,    74,    69,    73,    72,    71,    70,
   nil,   nil,    66,    65,    64,   nil,   nil,    74,    69,    73,
    72,    71,    70,   nil,   nil,    66,    65,    64,    60,    61,
    62,    63,   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,
    67,    60,    61,    62,    63,   nil,   nil,   nil,   nil,   nil,
   nil,    68,   216,    67,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    74,    69,    73,    72,    71,    70,   nil,   nil,
    66,    65,    64,   nil,   nil,    74,    69,    73,    72,    71,
    70,   nil,   nil,    66,    65,    64,    60,    61,    62,    63,
   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,    67,    60,
    61,    62,    63,   nil,   nil,   nil,   nil,   nil,   nil,    68,
   nil,    67,   nil,   nil,   nil,   nil,   nil,   nil,   217,   nil,
    74,    69,    73,    72,    71,    70,   nil,   198,    66,    65,
    64,   nil,   nil,    74,    69,    73,    72,    71,    70,   nil,
   nil,    66,    65,    64,    60,    61,    62,    63,   nil,   nil,
   nil,   nil,   nil,   nil,    68,   nil,    67,    60,    61,    62,
    63,   nil,   nil,   nil,   nil,   nil,   nil,    68,   nil,    67,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    74,    69,
    73,    72,    71,    70,   nil,   nil,    66,    65,    64,   nil,
   nil,    74,    69,    73,    72,    71,    70,   nil,   nil,    66,
    65,    64 ]

racc_action_check = [
   118,   118,   118,   118,    22,    16,    22,    15,    15,    22,
   118,    26,   118,    22,    22,    98,    22,    98,    15,    93,
    98,    96,     0,    96,    98,    98,    96,    98,    93,   157,
    96,    96,    51,    96,   118,   118,   118,   118,   118,   118,
    51,    16,   118,   118,   118,   132,   132,    26,   154,   118,
    22,    22,    99,    99,   179,   143,   179,   197,   151,   179,
   143,    98,    98,   179,   179,   197,   179,    96,    96,   178,
   147,   178,   100,   100,   178,    23,   167,    23,   178,   178,
    23,   178,   196,   168,    23,    23,    69,    23,    69,   144,
   196,    69,    99,    99,    99,    69,    69,    65,    69,    65,
   179,   179,    65,    56,   142,   225,    65,    65,   140,    65,
   225,    56,   100,   100,   100,   178,   178,   133,    12,   177,
    12,    23,    23,    12,    40,    40,   130,    12,    12,   128,
    12,   125,    69,   124,    12,    12,    12,    12,   170,   170,
    12,    12,    12,    65,    12,    12,    12,   183,   217,   170,
   217,   145,   145,   217,    91,    91,   116,   217,   217,   114,
   217,   146,   146,   186,    12,   217,   217,   217,    92,   188,
   217,   217,   217,   189,   217,   217,   217,    89,    14,   191,
    14,   217,   192,    14,    87,   195,    85,    14,    14,    84,
    14,    78,   200,   156,   217,    14,    14,    14,    55,    50,
    14,    14,    14,    49,    14,    14,    14,   207,   171,    45,
   171,   209,    41,   171,    28,    21,    13,   171,   171,   218,
   171,   220,   222,     9,    14,   171,   171,   171,   224,     6,
   171,   171,   171,   226,   171,   171,   171,   227,   139,   228,
   139,   171,     5,   139,   230,   231,     4,   139,   139,     3,
   139,   239,   240,   241,   171,   139,   139,   139,     1,   244,
   139,   139,   139,   245,   139,   139,   139,   nil,   216,   nil,
   216,   nil,   nil,   216,   nil,   nil,   nil,   216,   216,   nil,
   216,   nil,   nil,   nil,   139,   216,   216,   216,   nil,   nil,
   216,   216,   216,   nil,   216,   216,   216,   nil,   nil,   nil,
     7,   216,     7,   nil,   nil,     7,   nil,   nil,   nil,     7,
     7,   nil,     7,   nil,   216,   nil,     7,     7,     7,     7,
   nil,   nil,     7,     7,     7,   nil,     7,     7,     7,   138,
   nil,   138,   nil,   nil,   138,   174,   nil,   174,   138,   138,
   174,   138,   nil,   nil,   174,   174,     7,   174,    27,   nil,
    27,   nil,   nil,    27,   215,   nil,   215,    27,    27,   215,
    27,   nil,   nil,   215,   215,   nil,   215,    29,   nil,    29,
   nil,   nil,    29,   nil,   nil,   138,    29,    29,    30,    29,
    30,   174,   nil,    30,   nil,   nil,   nil,    30,    30,   nil,
    30,   nil,   nil,    33,    27,    33,   nil,   nil,    33,    34,
   215,    34,    33,    33,    34,    33,   nil,   nil,    34,    34,
    35,    34,    35,    29,   nil,    35,   nil,   nil,   nil,    35,
    35,   nil,    35,   nil,    30,   159,   nil,   159,   nil,   nil,
   159,   nil,   nil,   nil,   159,   159,   nil,   159,   nil,    33,
   nil,   nil,   159,   159,   159,    34,   nil,   159,   159,   159,
   nil,   159,   159,   159,   nil,   214,    35,   214,   159,   nil,
   214,   nil,   nil,   nil,   214,   214,   nil,   214,   nil,   nil,
   nil,   159,   214,   214,   214,   nil,   nil,   214,   214,   214,
   nil,   214,   214,   214,   nil,   nil,   nil,    44,   214,    44,
   nil,   nil,    44,   nil,   nil,   nil,    44,    44,   nil,    44,
   nil,   214,   nil,    44,    44,    44,    44,   nil,   nil,    44,
    44,    44,   nil,    44,    44,    44,   nil,   208,   nil,   208,
   nil,   nil,   208,   nil,   nil,   nil,   208,   208,   nil,   208,
   nil,   nil,   nil,    44,   208,   208,   208,   nil,   nil,   208,
   208,   208,   nil,   208,   208,   208,   nil,   nil,   nil,    46,
   208,    46,   nil,   nil,    46,   nil,   nil,   nil,    46,    46,
   nil,    46,   nil,   208,   nil,    46,    46,    46,    46,   nil,
   nil,    46,    46,    46,   nil,    46,    46,    46,   229,   nil,
   229,   nil,   nil,   229,   203,   nil,   203,   229,   229,   203,
   229,   nil,   nil,   203,   203,    46,   203,   nil,   nil,   nil,
   nil,   203,   203,   203,   nil,   nil,   203,   203,   203,   nil,
   203,   203,   203,   nil,   nil,   nil,   127,   nil,   127,   nil,
   nil,   127,   nil,   nil,   229,   127,   127,   nil,   127,   nil,
   203,   nil,   127,   127,   127,   127,   nil,   nil,   127,   127,
   127,   nil,   127,   127,   127,   182,   nil,   182,   nil,   nil,
   182,   122,   nil,   122,   182,   182,   122,   182,   nil,   nil,
   122,   122,   127,   122,   nil,   nil,   nil,   nil,   122,   122,
   122,   nil,   nil,   122,   122,   122,   nil,   122,   122,   122,
   nil,   nil,   nil,   121,   nil,   121,   nil,   nil,   121,   nil,
   nil,   182,   121,   121,   nil,   121,   nil,   122,   nil,   nil,
   121,   121,   121,   nil,   nil,   121,   121,   121,   nil,   121,
   121,   121,   120,   nil,   120,   nil,   nil,   120,    60,   nil,
    60,   120,   120,    60,   120,   nil,   nil,    60,    60,   121,
    60,    61,   nil,    61,   nil,   nil,    61,    62,   nil,    62,
    61,    61,    62,    61,   nil,   nil,    62,    62,   nil,    62,
    63,   nil,    63,   nil,   nil,    63,   nil,   nil,   120,    63,
    63,    64,    63,    64,    60,   nil,    64,   nil,   nil,   nil,
    64,    64,   nil,    64,   nil,   nil,   119,    61,   119,   nil,
   nil,   119,   nil,    62,   nil,   119,   119,   nil,   119,   nil,
   nil,   nil,   nil,   119,   119,   119,    63,   nil,   119,   119,
   119,   nil,   119,   119,   119,   nil,    66,    64,    66,   nil,
   nil,    66,   nil,   nil,   nil,    66,    66,   nil,    66,    67,
   nil,    67,   119,   nil,    67,    68,   nil,    68,    67,    67,
    68,    67,   nil,   nil,    68,    68,   169,    68,   169,   nil,
   nil,   169,   nil,   nil,   nil,   169,   169,   nil,   169,   nil,
   nil,   nil,    66,   169,   169,   169,   nil,   nil,   169,   169,
   169,   nil,   169,   169,   169,    67,   nil,   nil,    70,   169,
    70,    68,   nil,    70,    71,   nil,    71,    70,    70,    71,
    70,   nil,   169,    71,    71,    72,    71,    72,   nil,   nil,
    72,    73,   nil,    73,    72,    72,    73,    72,   nil,   nil,
    73,    73,   nil,    73,   nil,   nil,    74,   nil,    74,   nil,
   nil,    74,   nil,   nil,    70,    74,    74,    75,    74,    75,
    71,   nil,    75,   nil,   nil,   nil,    75,    75,   nil,    75,
    76,    72,    76,   nil,   nil,    76,    76,    73,   nil,    76,
    76,   184,    76,   184,   nil,   nil,   184,   nil,   nil,   nil,
   184,   184,    74,   184,   nil,   232,   nil,   232,   nil,   nil,
   232,   nil,   nil,    75,   232,   232,   nil,   232,   nil,   nil,
   nil,   nil,   232,   232,   232,   nil,    76,   232,   232,   232,
   nil,   232,   232,   232,   185,   nil,   185,   184,   232,   185,
   190,   nil,   190,   185,   185,   190,   185,   nil,   nil,   190,
   190,   232,   190,   nil,   nil,   nil,   190,   190,   190,   190,
   nil,   nil,   190,   190,   190,   nil,   190,   190,   190,   nil,
   nil,   nil,   158,   190,   158,   nil,   nil,   158,   nil,   nil,
   185,   158,   158,   nil,   158,   nil,   190,   nil,   nil,   158,
   158,   158,   nil,   nil,   158,   158,   158,   nil,   158,   158,
   158,   nil,   242,   nil,   242,   nil,   nil,   242,   nil,   nil,
   nil,   242,   242,   nil,   242,   nil,   nil,   nil,   158,   242,
   242,   242,   nil,   nil,   242,   242,   242,   nil,   242,   242,
   242,   187,   nil,   187,   nil,   242,   187,    90,   nil,    90,
   187,   187,    90,   187,   nil,   nil,    90,    90,   242,    90,
   nil,   nil,   nil,    90,    90,    90,    90,   nil,   nil,    90,
    90,    90,   nil,    90,    90,    90,   nil,   nil,   nil,    88,
   nil,    88,   nil,   nil,    88,   nil,   nil,   187,    88,    88,
   nil,    88,   nil,    90,   nil,    88,    88,    88,    88,   nil,
   nil,    88,    88,    88,   nil,    88,    88,    88,   155,   nil,
   155,   nil,   nil,   155,   nil,   nil,   nil,   155,   155,   nil,
   155,   194,   194,   194,   194,    88,   nil,   nil,   nil,   nil,
   nil,   194,   nil,   194,   nil,   nil,   236,   236,   236,   236,
   nil,   nil,   nil,   nil,   nil,   nil,   236,   nil,   236,   nil,
   nil,   nil,   nil,   nil,   155,   194,   194,   194,   194,   194,
   194,   nil,   194,   194,   194,   194,   236,   nil,   nil,   nil,
   236,   236,   236,   236,   236,   236,   nil,   nil,   236,   236,
   236,   164,   164,   164,   164,   nil,   nil,   nil,   nil,   nil,
   nil,   164,   nil,   164,   nil,   nil,   nil,   223,   223,   223,
   223,   nil,   nil,   nil,   nil,   nil,   nil,   223,   nil,   223,
   nil,   164,   nil,   nil,   nil,   164,   164,   164,   164,   164,
   164,   nil,   nil,   164,   164,   164,   223,   nil,   nil,   nil,
   nil,   223,   223,   223,   223,   223,   223,   nil,   nil,   223,
   223,   223,   141,   141,   141,   141,   nil,   nil,   nil,   nil,
   nil,   nil,   141,   nil,   141,    83,    83,    83,    83,   nil,
    83,   nil,   nil,   nil,   nil,    83,   nil,    83,   nil,   nil,
   nil,   141,   nil,   nil,   nil,   nil,   141,   141,   141,   141,
   141,   141,   nil,   nil,   141,   141,   141,   nil,   nil,    83,
    83,    83,    83,    83,    83,   nil,   nil,    83,    83,    83,
    25,    25,    25,    25,   nil,   nil,   nil,   nil,   nil,   nil,
    25,   nil,    25,   204,   204,   204,   204,   nil,   nil,   nil,
   nil,   nil,   nil,   204,   nil,   204,   nil,   nil,   nil,   nil,
   106,   106,   106,   106,    25,    25,    25,    25,    25,    25,
   106,    25,    25,    25,    25,   nil,   nil,   204,   204,   204,
   204,   204,   204,   nil,   nil,   204,   204,   204,   107,   107,
   107,   107,   nil,   nil,   106,   106,   106,   106,   106,   106,
   nil,   nil,   106,   106,   106,   108,   108,   108,   108,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   109,   109,   109,   109,
   nil,   nil,   107,   107,   107,   107,   107,   107,   nil,   nil,
   107,   107,   107,   110,   110,   110,   110,   nil,   nil,   108,
   108,   108,   108,   108,   108,   nil,   nil,   108,   108,   108,
   109,   109,   109,   109,   109,   109,   nil,   nil,   109,   109,
   109,   111,   111,   111,   111,   nil,   nil,   110,   110,   110,
   110,   110,   110,   nil,   nil,   110,   110,   110,   112,   112,
   112,   112,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   113,
   113,   113,   113,   nil,   nil,   111,   111,   111,   111,   111,
   111,   nil,   nil,   111,   111,   111,   nil,   nil,   nil,   nil,
   nil,   nil,   112,   112,   112,   112,   112,   112,   nil,   nil,
   112,   112,   112,   113,   113,   113,   113,   113,   113,   nil,
   nil,   113,   113,   113,    80,    80,    80,    80,   nil,   nil,
   nil,   nil,   nil,   nil,    80,   nil,    80,   nil,   nil,   nil,
   nil,   nil,   nil,    80,   nil,    79,    79,    79,    79,   nil,
   nil,   nil,   nil,   nil,   nil,    79,   nil,    79,    80,    80,
    80,    80,    80,    80,   nil,   nil,    80,    80,    80,    79,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    79,
    79,    79,    79,    79,    79,   nil,   nil,    79,    79,    79,
   199,   199,   199,   199,   nil,   nil,   nil,   nil,   nil,   nil,
   199,   nil,   199,    77,    77,    77,    77,   199,   nil,   nil,
   nil,   nil,   nil,    77,   nil,    77,   nil,   nil,   nil,   nil,
    77,   nil,   nil,   nil,   199,   199,   199,   199,   199,   199,
   nil,   nil,   199,   199,   199,   nil,   nil,    77,    77,    77,
    77,    77,    77,   nil,   nil,    77,    77,    77,   201,   201,
   201,   201,   nil,   nil,   nil,   nil,   nil,   nil,   201,   nil,
   201,    57,    57,    57,    57,   nil,   nil,   nil,   nil,   nil,
   nil,    57,   201,    57,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   201,   201,   201,   201,   201,   201,   nil,   nil,
   201,   201,   201,   nil,   nil,    57,    57,    57,    57,    57,
    57,   nil,   nil,    57,    57,    57,   181,   181,   181,   181,
   nil,   nil,   nil,   nil,   nil,   nil,   181,   nil,   181,   202,
   202,   202,   202,   nil,   nil,   nil,   nil,   nil,   nil,   202,
   nil,   202,   nil,   nil,   nil,   nil,   nil,   nil,   202,   nil,
   181,   181,   181,   181,   181,   181,   nil,   181,   181,   181,
   181,   nil,   nil,   202,   202,   202,   202,   202,   202,   nil,
   nil,   202,   202,   202,    52,    52,    52,    52,   nil,   nil,
   nil,   nil,   nil,   nil,    52,   nil,    52,   115,   115,   115,
   115,   nil,   nil,   nil,   nil,   nil,   nil,   115,   nil,   115,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    52,    52,
    52,    52,    52,    52,   nil,   nil,    52,    52,    52,   nil,
   nil,   115,   115,   115,   115,   115,   115,   nil,   nil,   115,
   115,   115 ]

racc_action_pointer = [
   -12,   258,   nil,   233,   212,   194,   229,   298,   nil,   216,
   nil,   nil,   116,   172,   176,    -2,    -2,   nil,   nil,   nil,
   nil,   167,     2,    73,   nil,  1337,     4,   346,   166,   365,
   376,   nil,   nil,   391,   397,   408,   nil,   nil,   nil,   nil,
   115,   168,   nil,   nil,   485,   189,   547,   nil,   nil,   155,
   155,   -12,  1781,   nil,   nil,   191,    59,  1678,   nil,   nil,
   716,   729,   735,   748,   759,    95,   804,   817,   823,    84,
   866,   872,   883,   889,   904,   915,   928,  1620,   160,  1562,
  1541,   nil,   nil,  1292,   181,   138,   nil,   140,  1117,   133,
  1085,   145,   124,   -24,   nil,   nil,    19,   nil,    13,    47,
    67,   nil,   nil,   nil,   nil,   nil,  1367,  1395,  1412,  1423,
  1440,  1468,  1485,  1496,   115,  1794,   148,   nil,    -3,   774,
   710,   681,   649,   nil,    97,    79,   nil,   614,    85,   nil,
    82,   nil,    36,    69,   nil,   nil,   nil,   nil,   327,   236,
    90,  1279,    86,    37,    72,   142,   152,    26,   nil,   nil,
   nil,     6,   nil,   nil,     4,  1146,   149,   -15,  1020,   423,
   nil,   nil,   nil,   nil,  1218,   nil,   nil,    58,    65,   834,
   129,   206,   nil,   nil,   333,   nil,   nil,    71,    67,    52,
   nil,  1723,   643,    99,   939,   982,   143,  1079,   125,   129,
   988,   159,   164,   nil,  1158,   141,    38,    13,   nil,  1607,
   161,  1665,  1736,   582,  1350,   nil,   nil,   163,   515,   167,
   nil,   nil,   nil,   nil,   453,   352,   266,   146,   201,   nil,
   203,   nil,   204,  1234,   210,    87,   189,   193,   195,   576,
   200,   201,   953,   nil,   nil,   nil,  1173,   nil,   nil,   233,
   232,   209,  1050,   nil,   241,   219,   nil ]

racc_action_default = [
    -4,  -104,    -1,  -104,    -4,  -104,  -104,  -104,    -5,  -104,
   -18,   247,  -104,  -104,  -104,  -104,  -102,   -44,   -46,   -47,
   -48,  -104,  -104,  -104,   -52,  -104,  -104,  -104,  -104,  -104,
  -104,   -79,   -80,  -104,  -104,  -104,   -99,  -100,  -101,  -103,
   -15,  -104,   -45,    -3,  -104,  -104,  -104,   -19,   -20,  -104,
  -104,  -104,   -54,   -55,   -60,  -104,  -104,   -57,   -58,   -53,
  -104,  -104,  -104,  -104,  -104,  -104,  -104,  -104,  -104,  -104,
  -104,  -104,  -104,  -104,  -104,  -104,  -104,  -104,  -104,  -104,
  -104,   -88,   -89,  -104,  -104,  -104,    -2,  -104,  -104,  -104,
  -104,   -21,  -104,   -25,   -49,   -50,  -104,   -51,  -104,   -81,
   -82,   -83,   -84,   -85,   -86,   -87,   -91,   -92,   -93,   -94,
   -95,   -96,   -97,   -98,  -104,   -62,  -104,   -76,   -77,   -42,
  -104,   -42,   -42,   -90,   -27,   -16,    -7,  -104,  -104,   -10,
  -104,   -22,   -23,  -104,   -56,   -59,   -61,   -75,  -104,   -43,
  -104,  -104,  -104,  -104,  -104,  -104,   -15,  -104,    -9,   -11,
   -24,   -25,   -26,   -78,  -104,  -104,  -104,  -104,   -42,   -29,
   -28,   -17,    -8,   -63,   -69,   -65,   -71,  -104,  -104,  -104,
  -104,   -30,   -31,   -33,  -104,   -35,   -36,  -104,  -104,  -104,
   -40,  -104,  -104,  -104,  -104,  -104,  -104,  -104,  -104,  -104,
  -104,  -104,  -104,   -32,  -104,  -104,  -104,  -104,   -41,  -104,
  -104,  -104,  -104,   -42,   -70,   -72,    -6,  -104,   -29,  -104,
   -34,   -37,   -38,   -39,   -29,  -104,   -29,   -29,  -104,   -12,
  -104,   -14,  -104,  -104,  -104,  -104,  -104,  -104,  -104,  -104,
  -104,  -104,   -29,   -64,   -13,   -66,   -69,   -68,   -73,  -104,
  -104,  -104,   -29,   -74,  -104,  -104,   -67 ]

racc_goto_table = [
     9,    51,    26,    58,    56,    84,    45,    26,    92,    26,
   140,   116,   142,   143,    85,    12,    50,   186,   193,   144,
     3,   190,    44,    78,     8,   114,     2,     1,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   193,   nil,    26,
    42,    26,   nil,   nil,    93,   nil,   nil,   nil,   nil,   167,
   nil,   nil,   nil,   nil,    90,    91,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    42,   153,   nil,   134,   nil,   nil,    58,   135,
   125,   nil,   131,    26,   nil,    26,   nil,   nil,   nil,   240,
   nil,   nil,   152,   nil,   218,   nil,   127,    52,    57,   nil,
   nil,   nil,    77,   nil,    79,    80,   nil,   nil,    81,    82,
    83,   161,   nil,   nil,    26,   nil,    26,    26,    42,   160,
    85,   nil,    26,   150,   nil,   nil,   nil,   nil,   151,   nil,
   nil,   nil,   168,   nil,    26,    99,   100,   101,   102,   103,
   104,   105,   106,   107,   108,   109,   110,   111,   112,   113,
   115,   118,   nil,    26,    26,    42,   nil,   196,   nil,    58,
   197,   191,   nil,   nil,    26,   175,    26,    42,   nil,   nil,
   nil,    52,   195,    57,   nil,   175,   nil,   175,   200,   nil,
   nil,   220,   nil,   nil,   nil,    26,   nil,   222,   nil,   224,
   225,   nil,   nil,   nil,   nil,   141,   175,   nil,    26,   nil,
   nil,   nil,   nil,    26,   nil,   239,   nil,   nil,   nil,    26,
   nil,    26,    26,   118,   175,   244,   nil,   nil,   nil,   nil,
   175,   nil,   175,   175,   nil,   nil,   nil,    26,   nil,   nil,
   164,   nil,   nil,   nil,   181,   nil,   nil,    26,   175,   nil,
   nil,   nil,   nil,   nil,   181,   nil,   181,   nil,   175,   194,
   nil,   nil,   nil,    52,    57,   nil,   nil,   199,   nil,   201,
   202,   nil,   204,   nil,   nil,   181,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   181,   nil,   nil,   nil,   nil,   nil,   181,
   223,   181,   181,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   236,   nil,   nil,   181,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   181 ]

racc_goto_check = [
     6,    20,     6,    27,    21,     7,    11,     6,    16,     6,
    23,    31,    23,    23,    14,     4,     6,    29,    17,     8,
     3,    13,     4,     6,     3,    28,     2,     1,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    17,   nil,     6,
    24,     6,   nil,   nil,     6,   nil,   nil,   nil,   nil,    23,
   nil,   nil,   nil,   nil,     4,    15,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    24,    31,   nil,    20,   nil,   nil,    27,    21,
     6,   nil,    11,     6,   nil,     6,   nil,   nil,   nil,    29,
   nil,   nil,    16,   nil,    23,   nil,     4,    18,    18,   nil,
   nil,   nil,    18,   nil,    18,    18,   nil,   nil,    18,    18,
    18,     7,   nil,   nil,     6,   nil,     6,     6,    24,    14,
    14,   nil,     6,    11,   nil,   nil,   nil,   nil,     6,   nil,
   nil,   nil,     9,   nil,     6,    18,    18,    18,    18,    18,
    18,    18,    18,    18,    18,    18,    18,    18,    18,    18,
    18,    18,   nil,     6,     6,    24,   nil,    20,   nil,    27,
    21,    11,   nil,   nil,     6,    15,     6,    24,   nil,   nil,
   nil,    18,     6,    18,   nil,    15,   nil,    15,     6,   nil,
   nil,     9,   nil,   nil,   nil,     6,   nil,     9,   nil,     9,
     9,   nil,   nil,   nil,   nil,    18,    15,   nil,     6,   nil,
   nil,   nil,   nil,     6,   nil,     9,   nil,   nil,   nil,     6,
   nil,     6,     6,    18,    15,     9,   nil,   nil,   nil,   nil,
    15,   nil,    15,    15,   nil,   nil,   nil,     6,   nil,   nil,
    18,   nil,   nil,   nil,    18,   nil,   nil,     6,    15,   nil,
   nil,   nil,   nil,   nil,    18,   nil,    18,   nil,    15,    18,
   nil,   nil,   nil,    18,    18,   nil,   nil,    18,   nil,    18,
    18,   nil,    18,   nil,   nil,    18,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,    18,
    18,    18,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    18,   nil,   nil,    18,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18 ]

racc_goto_pointer = [
   nil,    27,    26,    20,     8,   nil,    -5,   -35,  -105,   -27,
   nil,    -9,   nil,  -148,   -26,     6,   -41,  -153,    75,   nil,
   -21,   -19,   nil,  -109,    28,   nil,   nil,   -20,   -50,  -147,
   nil,   -65,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   139,     4,    55,   nil,   nil,   nil,
    18,   nil,   173,   171,    49,    19,   nil,   172,    25,   176,
   nil,   nil,   180,   nil,    17,    20,    24,    53,   nil,   nil,
    32,   nil,    31,    39 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 55, :_reduce_1,
  5, 56, :_reduce_2,
  4, 56, :_reduce_3,
  0, 57, :_reduce_none,
  2, 57, :_reduce_5,
  10, 59, :_reduce_6,
  4, 64, :_reduce_7,
  6, 64, :_reduce_8,
  5, 64, :_reduce_9,
  4, 64, :_reduce_10,
  5, 64, :_reduce_11,
  4, 66, :_reduce_12,
  6, 66, :_reduce_13,
  4, 66, :_reduce_14,
  0, 61, :_reduce_none,
  2, 61, :_reduce_16,
  4, 61, :_reduce_17,
  1, 60, :_reduce_18,
  1, 68, :_reduce_19,
  1, 68, :_reduce_20,
  2, 65, :_reduce_21,
  3, 65, :_reduce_22,
  3, 65, :_reduce_23,
  4, 65, :_reduce_24,
  1, 70, :_reduce_25,
  3, 70, :_reduce_26,
  0, 62, :_reduce_none,
  2, 62, :_reduce_28,
  0, 63, :_reduce_none,
  1, 63, :_reduce_none,
  1, 67, :_reduce_31,
  2, 67, :_reduce_32,
  1, 71, :_reduce_33,
  3, 71, :_reduce_34,
  1, 71, :_reduce_35,
  1, 71, :_reduce_36,
  3, 71, :_reduce_37,
  3, 71, :_reduce_38,
  3, 71, :_reduce_39,
  1, 71, :_reduce_40,
  2, 71, :_reduce_41,
  0, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 58, :_reduce_44,
  2, 58, :_reduce_45,
  1, 78, :_reduce_46,
  1, 78, :_reduce_47,
  1, 78, :_reduce_48,
  3, 78, :_reduce_49,
  3, 78, :_reduce_50,
  3, 78, :_reduce_51,
  1, 78, :_reduce_52,
  2, 78, :_reduce_53,
  1, 74, :_reduce_54,
  1, 74, :_reduce_55,
  3, 74, :_reduce_56,
  1, 75, :_reduce_57,
  1, 75, :_reduce_58,
  3, 75, :_reduce_59,
  1, 81, :_reduce_60,
  4, 69, :_reduce_61,
  1, 82, :_reduce_62,
  6, 79, :_reduce_63,
  11, 79, :_reduce_64,
  6, 79, :_reduce_65,
  6, 73, :_reduce_66,
  11, 73, :_reduce_67,
  6, 73, :_reduce_68,
  0, 83, :_reduce_none,
  2, 83, :_reduce_70,
  6, 80, :_reduce_71,
  8, 80, :_reduce_72,
  6, 76, :_reduce_73,
  8, 76, :_reduce_74,
  4, 84, :_reduce_75,
  3, 84, :_reduce_76,
  1, 85, :_reduce_77,
  3, 85, :_reduce_78,
  1, 72, :_reduce_none,
  1, 72, :_reduce_none,
  3, 72, :_reduce_81,
  3, 72, :_reduce_82,
  3, 72, :_reduce_83,
  3, 72, :_reduce_84,
  3, 72, :_reduce_85,
  3, 72, :_reduce_86,
  3, 72, :_reduce_87,
  2, 72, :_reduce_88,
  2, 72, :_reduce_89,
  3, 72, :_reduce_90,
  3, 72, :_reduce_91,
  3, 72, :_reduce_92,
  3, 72, :_reduce_93,
  3, 72, :_reduce_94,
  3, 72, :_reduce_95,
  3, 72, :_reduce_96,
  3, 72, :_reduce_97,
  3, 72, :_reduce_98,
  1, 87, :_reduce_99,
  1, 87, :_reduce_100,
  1, 86, :_reduce_101,
  1, 86, :_reduce_102,
  1, 86, :_reduce_none ]

racc_reduce_n = 104

racc_shift_n = 247

racc_token_table = {
  false => 0,
  :error => 1,
  :DIGIT => 2,
  :PLUS => 3,
  :LESS => 4,
  :MULT => 5,
  :DIV2 => 6,
  :LPARENT => 7,
  :RPARENT => 8,
  :TYPEN => 9,
  :TYPEB => 10,
  :TRUE => 11,
  :FALSE => 12,
  :AND => 13,
  :NOT => 14,
  :OR => 15,
  :PROGRAM => 16,
  :BEGIN => 17,
  :END => 18,
  :WITH => 19,
  :DO => 20,
  :IF => 21,
  :THEN => 22,
  :ELSE => 23,
  :WHILE => 24,
  :FOR => 25,
  :REPEAT => 26,
  :TIMES => 27,
  :READ => 28,
  :WRITE => 29,
  :WRITELN => 30,
  :FROM => 31,
  :TO => 32,
  :BY => 33,
  :FUNC => 34,
  :RETURN => 35,
  :RETURN2 => 36,
  :EQUIVALENT => 37,
  :LESSTHAN => 38,
  :DISTINCT => 39,
  :GETHAN => 40,
  :LETHAN => 41,
  :GREATTHAN => 42,
  :EQUAL => 43,
  :SEMICOLON => 44,
  :MOD => 45,
  :DIV => 46,
  :MOD2 => 47,
  :ID => 48,
  :STRING => 49,
  :LCURLY => 50,
  :RCURLY => 51,
  :COLON => 52,
  :UMINUS => 53 }

racc_nt_base = 54

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DIGIT",
  "PLUS",
  "LESS",
  "MULT",
  "DIV2",
  "LPARENT",
  "RPARENT",
  "TYPEN",
  "TYPEB",
  "TRUE",
  "FALSE",
  "AND",
  "NOT",
  "OR",
  "PROGRAM",
  "BEGIN",
  "END",
  "WITH",
  "DO",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "FOR",
  "REPEAT",
  "TIMES",
  "READ",
  "WRITE",
  "WRITELN",
  "FROM",
  "TO",
  "BY",
  "FUNC",
  "RETURN",
  "RETURN2",
  "EQUIVALENT",
  "LESSTHAN",
  "DISTINCT",
  "GETHAN",
  "LETHAN",
  "GREATTHAN",
  "EQUAL",
  "SEMICOLON",
  "MOD",
  "DIV",
  "MOD2",
  "ID",
  "STRING",
  "LCURLY",
  "RCURLY",
  "COLON",
  "UMINUS",
  "$start",
  "S",
  "Scope",
  "Listfunciones",
  "LInst",
  "funciones",
  "Var",
  "ListD",
  "Retorno",
  "funcInst",
  "wis",
  "Ldecl",
  "wisf",
  "LInstf",
  "type",
  "Assign",
  "ListID",
  "Instf",
  "Expr",
  "IteratorF",
  "writable1",
  "writable2",
  "CondF",
  "LInstruc",
  "Inst",
  "Iterator",
  "Cond",
  "Str",
  "Asignable",
  "by",
  "Call",
  "ListParam",
  "Term",
  "Bool" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'retina_parser.y', 43)
  def _reduce_1(val, _values, result)
    result = S.new(val[0]);$Close = Closeeye.new()
        $Open= Openeye.new();
        $Home = Home.new();
        $Forward = Forward.new();
        $Backward = Backward.new();
        $Setposition = Setposition.new();$Rotater=Rotater.new();$Rotatel=Rotatel.new()
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 53)
  def _reduce_2(val, _values, result)
    result = Scope.new(:Funciones,val[0],:Program,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 54)
  def _reduce_3(val, _values, result)
    result = Scope.new(:Funciones,val[0],nil,nil)
    result
  end
.,.,

# reduce 4 omitted

module_eval(<<'.,.,', 'retina_parser.y', 59)
  def _reduce_5(val, _values, result)
    result=ListaFunc.new(:Funcion,val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 63)
  def _reduce_6(val, _values, result)
    result=Func.new(:Nombre_Funcion,val[1],:Parametros,val[3],:Tipo_Retorno,val[5],:Instrucciones,val[7])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 67)
  def _reduce_7(val, _values, result)
    result=Bloque.new(:declaraciones,nil,:instrucciones,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 68)
  def _reduce_8(val, _values, result)
    result=Bloque.new(:declaraciones,val[1],:instrucciones,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 69)
  def _reduce_9(val, _values, result)
    result=Bloque.new(:declaraciones,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 70)
  def _reduce_10(val, _values, result)
    result=Bloque.new(:declaraciones,nil,:instrucciones,nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 71)
  def _reduce_11(val, _values, result)
    result=Bloque.new(:declaraciones,nil,:instrucciones,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 75)
  def _reduce_12(val, _values, result)
    result=Bloque.new(:declaraciones,nil,:instrucciones,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 76)
  def _reduce_13(val, _values, result)
    result=Bloque.new(:declaraciones,val[1],:instrucciones,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 77)
  def _reduce_14(val, _values, result)
    result=Bloque.new(:declaraciones,nil,:instrucciones,nil)
    result
  end
.,.,

# reduce 15 omitted

module_eval(<<'.,.,', 'retina_parser.y', 82)
  def _reduce_16(val, _values, result)
    result=ListD.new(:tipos,val[0],:identificadores,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 83)
  def _reduce_17(val, _values, result)
    result=List.new(:tipos,val[0],val[3],:identificadores,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 87)
  def _reduce_18(val, _values, result)
    result = Terms.new(:ID , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 91)
  def _reduce_19(val, _values, result)
    result=Type.new(:Tipo,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 92)
  def _reduce_20(val, _values, result)
    result=Type.new(:Tipo,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 96)
  def _reduce_21(val, _values, result)
    result=Ldecl.new(:declaracion,:tipo,val[0],:asignacion,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 97)
  def _reduce_22(val, _values, result)
    result=Ldecl.new(:declaracion,:tipo,val[0],:asignacion,val[1],:declaracion,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 98)
  def _reduce_23(val, _values, result)
    result=Ldecl.new(:declaracion,:tipo,val[0],:Lista_ID,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 99)
  def _reduce_24(val, _values, result)
    result=Ldecl.new(:Lista_Decl,:tipo,val[0],:Lista_ID,val[1],:declaracion,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 103)
  def _reduce_25(val, _values, result)
    result=ListID.new(:ID,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 104)
  def _reduce_26(val, _values, result)
    result=ListID.new(:ID,val[0],val[2])
    result
  end
.,.,

# reduce 27 omitted

module_eval(<<'.,.,', 'retina_parser.y', 109)
  def _reduce_28(val, _values, result)
    result=Retorno.new(:tipo,val[1])
    result
  end
.,.,

# reduce 29 omitted

# reduce 30 omitted

module_eval(<<'.,.,', 'retina_parser.y', 119)
  def _reduce_31(val, _values, result)
    result=ListaInst.new(:Instruccion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 120)
  def _reduce_32(val, _values, result)
    result=ListaInst.new(:Instruccion,val[1],val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 124)
  def _reduce_33(val, _values, result)
    result=InstWis.new(:Bloque,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 125)
  def _reduce_34(val, _values, result)
    result=InstReturn.new(:Retorno,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 126)
  def _reduce_35(val, _values, result)
    result=InstAsign.new(:Asignacion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 127)
  def _reduce_36(val, _values, result)
    result=Inst.new(:Iteracion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 128)
  def _reduce_37(val, _values, result)
    result=Read.new(:Lectura,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 129)
  def _reduce_38(val, _values, result)
    result=Write.new(:Salida,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 130)
  def _reduce_39(val, _values, result)
    result=WriteSalto.new(:Salida_Con_Salto,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 131)
  def _reduce_40(val, _values, result)
    result=Inst.new(:Condicional,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 132)
  def _reduce_41(val, _values, result)
    result=Inst.new(:Expresion,val[0])
    result
  end
.,.,

# reduce 42 omitted

# reduce 43 omitted

module_eval(<<'.,.,', 'retina_parser.y', 141)
  def _reduce_44(val, _values, result)
    result=ListaInst.new(:Instruccion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 142)
  def _reduce_45(val, _values, result)
    result=ListaInst.new(:Instruccion,val[1],val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 147)
  def _reduce_46(val, _values, result)
    result=InstWis.new(:Bloque,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 148)
  def _reduce_47(val, _values, result)
    result=InstAsign.new(:Asignacion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 149)
  def _reduce_48(val, _values, result)
    result=Inst.new(:Iteracion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 150)
  def _reduce_49(val, _values, result)
    result=Read.new(:Lectura,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 151)
  def _reduce_50(val, _values, result)
    result=Write.new(:Salida,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 152)
  def _reduce_51(val, _values, result)
    result=WriteSalto.new(:Salida_Con_Salto,val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 153)
  def _reduce_52(val, _values, result)
    result=Inst.new(:Condicional,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 154)
  def _reduce_53(val, _values, result)
    result=Inst.new(:Expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 158)
  def _reduce_54(val, _values, result)
    result=Writable.new(:Expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 159)
  def _reduce_55(val, _values, result)
    result=Writable.new(:String,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 160)
  def _reduce_56(val, _values, result)
    result=Writable.new(:valor,val[0],:valor,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 164)
  def _reduce_57(val, _values, result)
    result=Writable2.new(:Expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 165)
  def _reduce_58(val, _values, result)
    result=Writable2.new(:String,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 166)
  def _reduce_59(val, _values, result)
    result=Writable.new(:valor,val[0],:valor,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 171)
  def _reduce_60(val, _values, result)
    result=Str.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 175)
  def _reduce_61(val, _values, result)
    result=Assign.new(:Lado_Izquierdo,val[0],:Lado_Derecho,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 179)
  def _reduce_62(val, _values, result)
    result=Asignable_Expr.new(:Expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 183)
  def _reduce_63(val, _values, result)
    result=WLoop.new(:Ciclo_While,:Condicion,val[1],:Do,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 184)
  def _reduce_64(val, _values, result)
    result= FLoop.new(:Ciclo_For,:For,val[1],:From,val[3],:To,val[5],:By,val[6],:Instrucciones,val[8])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 185)
  def _reduce_65(val, _values, result)
    result=RLoop.new(:Ciclo_Repeat,:Times,val[1],:Instrucciones,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 189)
  def _reduce_66(val, _values, result)
    result=WLoop.new(:Ciclo_While,:Condicion,val[1],:Do,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 190)
  def _reduce_67(val, _values, result)
    result= FLoop.new(:Ciclo_For,:For,val[1],:From,val[3],:To,val[5],:By,val[6],:Instrucciones,val[8])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 191)
  def _reduce_68(val, _values, result)
    result=RLoop.new(:Ciclo_Repeat,:Times,val[1],:Instrucciones,val[3])
    result
  end
.,.,

# reduce 69 omitted

module_eval(<<'.,.,', 'retina_parser.y', 196)
  def _reduce_70(val, _values, result)
    result=By.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 200)
  def _reduce_71(val, _values, result)
    result=Cond.new(:Condición,val[1],:Instrucciones,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 201)
  def _reduce_72(val, _values, result)
    result=Cond.new(:Condicion,val[1],:Instrucciones,val[3],:Instrucciones_Else,val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 205)
  def _reduce_73(val, _values, result)
    result=Cond.new(:Condición,val[1],:Instrucciones,val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 206)
  def _reduce_74(val, _values, result)
    result=Cond.new(:Condicion,val[1],:Instrucciones,val[3],:Instrucciones_Else,val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 210)
  def _reduce_75(val, _values, result)
    result=Call.new(:nombre,val[0],:argumentos,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 211)
  def _reduce_76(val, _values, result)
    result=Call.new(:nombre,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 215)
  def _reduce_77(val, _values, result)
    result=ListParam.new(:expresion,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 216)
  def _reduce_78(val, _values, result)
    result=ListParam.new(:expresion,val[0],val[2])
    result
  end
.,.,

# reduce 79 omitted

# reduce 80 omitted

module_eval(<<'.,.,', 'retina_parser.y', 227)
  def _reduce_81(val, _values, result)
    result = BinExpSuma.new(:Suma, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 228)
  def _reduce_82(val, _values, result)
    result = BinExpResta.new(:Resta, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 229)
  def _reduce_83(val, _values, result)
    result = BinExpMult.new(:Multiplicacion, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 230)
  def _reduce_84(val, _values, result)
    result = BinExpDiv2.new(:Division_Exacta, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 231)
  def _reduce_85(val, _values, result)
    result = BinExpMod2.new(:Resto_Exacto, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 232)
  def _reduce_86(val, _values, result)
    result = BinExpDiv.new(:Division_Entera, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 233)
  def _reduce_87(val, _values, result)
    result = BinExpMod.new(:Resto_Entero, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 234)
  def _reduce_88(val, _values, result)
    result = UnaExp.new(:Inverso_Aditivo , val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 235)
  def _reduce_89(val, _values, result)
    result = UnaExp.new(:Negacion , val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 236)
  def _reduce_90(val, _values, result)
    result = ParExp.new(:Expresion, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 237)
  def _reduce_91(val, _values, result)
    result = BinExpOr.new(:Or , val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 238)
  def _reduce_92(val, _values, result)
    result = BinExpAnd.new(:And, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 239)
  def _reduce_93(val, _values, result)
    result = BinExpLT.new(:Menor_que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 240)
  def _reduce_94(val, _values, result)
    result = BinExpGT.new(:Mayor_que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 241)
  def _reduce_95(val, _values, result)
    result = BinExpLET.new(:Menor_O_Igual_Que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 242)
  def _reduce_96(val, _values, result)
    result = BinExpGET.new(:Mayor_O_Igual_Que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 243)
  def _reduce_97(val, _values, result)
    result = BinExpDist.new(:Distinto_Que, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 244)
  def _reduce_98(val, _values, result)
    result = BinExpEQ.new(:Equivalencia,val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 250)
  def _reduce_99(val, _values, result)
    result = Terms.new(:TRUE , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 251)
  def _reduce_100(val, _values, result)
    result = Terms.new(:FALSE , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 255)
  def _reduce_101(val, _values, result)
    result= Terms.new(:DIGIT,val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'retina_parser.y', 256)
  def _reduce_102(val, _values, result)
    result = Terms.new(:ID , val[0])
    result
  end
.,.,

# reduce 103 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
